bin/lib/log.js
bin/tester/runtimes.js

fixes: #8 
This changes the default loglevel (which also impact the output from test run)
It also makes this onfigurable via a ENV_VARIABLE

CHANGE default loglevel to 'error' and make it configurable

---

bin/main.js

fixes: #9 
Do a hard exit even if process build was a success

Exit hard after success, do not wait for bulky logs

---

bin/io/upload-to-s3.js

For #11
Probably hold off merging until 3.0.0 is out?

Manually retry uploads, recreating streams each time

---

bin/git/getCommitAndBranch.js

Add support for running in a github action

---

package.json

ADD chroma bin

---

.github/workflows/chromatic-push.yml
.github/workflows/chromatic.yml

This adds testers to make sure this package can run in a github action

Tech/add test for GitHub action

---

bin/lib/jsdom-shims.js

issue: https://github.com/chromaui/chromatic-cli/issues/27
solution found here: https://github.com/facebook/jest/issues/5379#issuecomment-360044161
not incuded in jsdom yet: https://github.com/jsdom/jsdom/issues/2128

ADD svg polyfills

---

bin/lib/jsdom-shims.js

https://github.com/chromaui/chromatic-cli/issues/48

Allow use of Intl without new operator

---

bin/git/git.js
bin/main.js
bin/tester/index.js
package.json

IMPROVE logging when git fails

---

bin/git/getCommitAndBranch.js

fixes: https://github.com/chromaui/chromatic-cli/issues/59

Use prBranch when available

---

bin/__tests__/tester.test.js
bin/tester/index.js

errorCount
specCount
componentCount
changeCount
buildNumber

ADD extra information about build to github action

---

bin/lib/jsdom-shims.js

FIX alwaysFn by copying static properties unto fn

---

bin/tester/runtimes.js

fixes: https://github.com/chromaui/chromatic-cli/issues/75#issuecomment-572265026

ADD throw on runtime errors

---

CHANGELOG.md
bin/git/getCommitAndBranch.js
package.json

FIX chromaui/action/issues/14

---

bin/tester/index.js

Another docs language update based on an error I saw come through support.

Update 'Storybook was not build' language

---

bin/lib/jsdom-shims.js

- Make most optional, maybe JSDOM is updated and already supports some of these.
- Extracted all mocks into their own function.
https://github.com/chromaui/chromatic-cli/issues/115

overhaul the jsdom shims

---

bin/io/upload-to-s3.js

For https://github.com/chromaui/chromatic/issues/3457

Set cache-control header on uploaded builds

---

.github/workflows/chromatic-action.yml
.github/workflows/chromatic-manual.yml
.github/workflows/chromatic-windows.yml
CHANGELOG.md
README.md
bin/git/getCommitAndBranch.js
bin/tester/index.js

FIX #119 - better messages during reporting in CLI

---

bin/git/git.js
bin/lib/package-json.js
package.json

Plain execSync has cross-platform issues. Execa eliminates those.
Fixes #137

Better cross platform compatibility for --patch-build

---

bin/lib/jsdom-shims.js

fix: https://github.com/chromaui/chromatic/issues/3587

ADD mock for execCommand

---

bin/tasks/build.js
bin/ui/messages/errors/buildFailed.js
bin/ui/messages/errors/buildFailed.stories.js
bin/ui/messages/errors/fatalError.js

Better error message for when build-storybook fails

---

bin/lib/utils.js
bin/main.js
bin/ui/messages/errors/missingStories.js
bin/ui/messages/errors/missingStories.stories.js
bin/ui/messages/errors/taskError.js

Handle 'no stories' error with custom messaging

---

bin/tasks/build.js
bin/ui/messages/errors/buildFailed.js
bin/ui/messages/errors/buildFailed.stories.js
bin/ui/messages/errors/fatalError.js
bin/ui/messages/errors/taskError.js
bin/ui/tasks/build.js

Fixes #167 and https://github.com/chromaui/chromatic/issues/3784

Improve error messages when build-storybook fails

---

.github/workflows/action-run.yml
.github/workflows/chromatic-action-test.yml
.github/workflows/chromatic-action.yml
.github/workflows/chromatic-staging-action.yml
action/main.ts

issue: #196
- add the event to our list of allowed events

ADD pull_request_review to list of allowed events

---

.github/workflows/action-run.yml
.github/workflows/chromatic-action-test.yml
.github/workflows/chromatic-action.yml
.github/workflows/chromatic-staging-action.yml
action/main.ts

issue: https://github.com/chromaui/chromatic-cli/issues/196
- add the event to our list of allowed events

ADD support for pull_request_target event

---

.github/workflows/chromatic-staging-action.yml
.github/workflows/chromatic-staging-manual.yml
.github/workflows/chromatic-staging-windows.yml
CHANGELOG.md
bin/lib/getEnv.js
bin/ui/tasks/tunnel.stories.js
package.json
stories/timing.stories-disabled.js
yarn.lock

fixes: https://github.com/chromaui/chromatic-cli/issues/281

revert meow upgrade

---

action/main.ts

issue: https://github.com/chromaui/chromatic-cli/issues/277

export the correct URL as storybookURL from the action

---

bin/lib/getStorybookInfo.js

fix #292 add @storybook/vue3 support

---

action.yml
action/main.js
action/main.ts
bin/lib/getOptions.js
bin/lib/parseArgs.js
bin/tasks/gitInfo.js
bin/tasks/gitInfo.test.js
bin/ui/messages/warnings/externalsChanged.js
bin/ui/messages/warnings/externalsChanged.stories.js

Fixes #340
Related: chromaui/chromatic-docs/pull/58

Ignore `onlyChanged` on changes matching `externals`

---

bin/git/git.js
bin/lib/getDependentStoryFiles.js
bin/lib/getDependentStoryFiles.test.js
bin/lib/utils.js
bin/tasks/gitInfo.test.js
package.json
scripts/publish-action.js

Support absolute paths in webpack stats

---

src/isChromatic.js

Fix isChromatic for server-side rendering

---

bin/ui/messages/errors/buildHasChanges.js

https://github.com/chromaui/chromatic-cli/issues/398
**New**
**Old**

Update BuildHasChanges message to be clearer

---

package.json
yarn.lock

https://github.com/node-fetch/node-fetch/pull/1301

Fix the version of `node-fetch` to `2.6.0` due to a bug in `2.6.3`

---

.github/workflows/chromatic-npx.yml
.github/workflows/chromatic-yarn-berry.yml
.github/workflows/chromatic-yarn-canary.yml
.github/workflows/chromatic-yarn-classic.yml
bin-src/lib/getInstalledStorybookPackages.ts
bin-src/lib/getStorybookInfo.js
bin-src/lib/promises.js
bin-src/register.js

This seems to have caused the issue in v6.0.0

fix the issue where require didn't work anymore

---

bin-src/lib/getDependentStoryFiles.js
bin-src/tasks/upload.js

Also log a better error if it doesn't work.

Deal with unnamed modules in stats file in webpack 5

---

bin-src/lib/compress.js
bin-src/lib/compress.test.js
bin-src/lib/getOptions.js
bin-src/lib/parseArgs.js
bin-src/lib/uploadZip.js
bin-src/tasks/upload.js
package.json
yarn.lock

This PR adds support for uploading a zip of all the Storybook artifacts which should speed up the publish step in most cases! 🎉

Support zip file upload CH-816 CH-817

---

bin-src/lib/compress.test.js

CircleCI wasn't happy about the tests with `mock-fs` (this worked locally 🙃 ).. this should fix it!

Fix tests of makeZipFile

---

bin-src/lib/parseArgs.js

Just a small description update to match our docs!

Change "upload" to "publish" CH-816 CH-817

---

action-src/README.md

As per https://github.com/chromaui/chromatic-cli/issues/471#issuecomment-989552898

Add `skip` documentation

---

action-src/main.ts

Fixes #486
Correcting a typo made in https://github.com/chromaui/chromatic-cli/commit/7d906e3ded08002a8514f2e7c346e44823da6899

Fix action option `storybookBaseDir`

---

bin-src/lib/writeChromaticDiagnostics.js
bin-src/stats-to-story-files.js

This fixes `npx chromatic stats-to-story-files` and prints diagnostics if it fails.

Fix `stats-to-story-files` util

---

README.md

Update with Gert fixes
Co-authored-by: Gert Hengeveld <info@ghengeveld.nl>

Add notes about how to use the `next` version

---

bin-src/git/getCommitAndBranch.ts
bin-src/ui/messages/warnings/noCommitDetails.stories.ts
bin-src/ui/messages/warnings/noCommitDetails.ts

See https://app.intercom.com/a/inbox/zj7sn9j1/inbox/shared/all/conversation/27254039631

Better `noCommitDetails` warning for custom GitHub `pull_request` workflows

---

action.yml
bin-src/lib/getOptions.ts
bin-src/lib/parseArgs.ts
bin-src/types.ts
bin-src/ui/messages/warnings/deprecatedOption.stories.ts
bin-src/ui/messages/warnings/deprecatedOption.ts

Deprecate `--preserve-missing` and raise a warning if it's being used

---

bin-src/tasks/gitInfo.ts
bin-src/ui/messages/info/forceRebuildHint.stories.ts
bin-src/ui/messages/info/forceRebuildHint.ts

This should clear up some confusion and help people on their way.

Suggest using `--force-rebuild` when skipping rebuild

---

bin-src/lib/getOptions.ts
bin-src/lib/parseArgs.ts
bin-src/tasks/snapshot.ts
bin-src/tasks/upload.test.ts
bin-src/tasks/upload.ts
bin-src/tasks/verify.ts
bin-src/types.ts
bin-src/ui/tasks/snapshot.stories.ts
bin-src/ui/tasks/snapshot.ts
bin-src/ui/tasks/upload.stories.ts
bin-src/ui/tasks/upload.ts
bin-src/ui/tasks/verify.stories.ts
bin-src/ui/tasks/verify.ts

Depends on https://github.com/chromaui/chromatic/pull/6405

Add `--only-story-files` flag

---

node-src/index.ts
node-src/runBuild.ts
package.json

Redo some of https://github.com/chromaui/chromatic-cli/pull/756

Fix issue with `onTaskComplete callback`

---

package.json

Add isChromatic exports

---

jest.config.js
package.json
yarn.lock

Fixes https://github.com/chromaui/chromatic-cli/issues/771
Second attempt at https://github.com/chromaui/chromatic-cli/pull/772

Bump loggly dep

---

.github/workflows/smoke-test-node18.yml
.github/workflows/smoke-test-node20.yml
.github/workflows/smoke-test-yarn-canary.yml
action.yml
node-src/tasks/upload.test.ts
node-src/tasks/upload.ts
package.json

For https://github.com/chromaui/chromatic/pull/7509

Send build id up with upload mutation

---

action-src/main.ts

closes: https://github.com/chromaui/chromatic-cli/issues/779

Add support for `schedule` GitHub Action workflow trigger

---

node-src/main.test.ts
node-src/runBuild.ts
node-src/types.ts
package.json

Add `experimental_` to `onTaskError`

---

action-src/main.ts

<details>
<summary>📦 Published PR as canary version: <code>7.5.5--canary.825.6709508815.0</code></summary>
<br />
```bash
npm install chromatic@7.5.5--canary.825.6709508815.0
yarn add chromatic@7.5.5--canary.825.6709508815.0
```
</details>

Merge Group (Queues) GitHub Action Event Support

---

bin-src/init.test.ts
bin-src/init.ts

<details>
<summary>📦 Published PR as canary version: <code>10.5.2--canary.902.7658557299.0</code></summary>
<br />
```bash
npm install chromatic@10.5.2--canary.902.7658557299.0
yarn add chromatic@10.5.2--canary.902.7658557299.0
```
</details>

Remove latest from the chromatic package in Init script

---

package.json
scripts/publish-action.mjs
yarn.lock

<details>
<summary>📦 Published PR as canary version: <code>11.5.1--canary.999.9352308866.0</code></summary>
<br />
```bash
npm install chromatic@11.5.1--canary.999.9352308866.0
yarn add chromatic@11.5.1--canary.999.9352308866.0
```
</details>

Clean package.json before publishing

---

node-src/lib/getDependentStoryFiles.test.ts
node-src/lib/getDependentStoryFiles.ts

Support storybook-rsbuild

---

bin-src/init.test.ts
bin-src/init.ts
node-src/index.ts
package.json
yarn.lock

Same package, new home. Bumps version as well.
<details>
<summary>📦 Published PR as canary version: <code>11.13.1--canary.1106.11447428930.0</code></summary>
<br />
```bash
npm install chromatic@11.13.1--canary.1106.11447428930.0
yarn add chromatic@11.13.1--canary.1106.11447428930.0
```
</details>

Switch to read-package-up from read-pkg-up
