chromaui/chromatic-cli

bin/lib/jsdom-shims.js

When running JSDOM multiple times, the shims are preserved.
In order to now cause an error, our shims have to be writable

CHANGE URL.createObjectURL to writable: true

---

bin/storybook/get-info.js

This resolves an issue a customer had.
The list of `viewLayers` should contain all storybook's supported frameworks.

ADD web-components as valid storybook app package name

---

bin/tester/index.js
package.json

set log-level of storybook build script to 'verbose' if log-level is set to verbose, otherwise to error

FIX loglevel

---

bin/tester/runtimes.js

Someone on support had this error come up and I noticed the verbiage was a bit off.

Update language on getRuntimeSpecs console output when hasErrors

---

.github/workflows/chromatic-action.yml
bin/lib/jsdom-shims.js

Hotfix for #115.
Do the minimum to make our `alwaysFn()` work with static methods.
To verify that `alwaysFn` works, try the following:
```js
const alwaysFn = /*  as defined */;
class A {
static method() {}
}
class B {}
const Bprime = alwaysFn(B);
Bprime.method();
```

Fix Intl mocks version 2

---

bin/io/gql-queries.js
bin/tester/index.js

This is meant to prevent users from ending up on the builds page while they're supposed to be following the onboarding flow.
This is only shown for build 1.
Also I removed the `.` after the link because my terminal was treating it as part of the URL when clicked.

Show "Continue setup at ..." link after running the very first build

---

README.md

The yarn remove command doesn't allow the `--dev` param and will throw an error if the documented code is run
`yarn remove --dev ...` > `yarn remove ...`

Fix yarn cmd in README

---

bin/git/git.js

This should hopefully avoid the `origin/*` prefix as well.

Better ways to retrieve the branch name

---

action.yml
action/main.js
action/main.ts

Thanks to the work of @yigityuce I created this pull request for monorepo support.
My editor automatically removes trailing whitespace at the end of each line, if necessary I could add them again, but then I would want to create a `.editorconfig` file.
Edit: See #181, #197, #209

Added monorepo support

---

bin/lib/parseArgs.js

This should allow us to upgrade to the latest version of meow again.

add explicit allow for multiple project-tokens (last will be used)

---

action.yml
action/README.md

Closes #293 
This PR documents Chromatic's GitHub action's outputs, both in the Readme and in the `action.yml` manifest. It also adds [a missing required field in the GitHub action schema](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputsinput_idrequired) – `required`.

Document GitHub action outputs

---

bin/tasks/build.js
bin/tasks/build.test.js

I don't know why, but yarn was not being correctly detected on my system (maybe because I'm using yarn 2?).
In my case, `process.env.npm_execpath` was returning `/path/to/yarn` rather than `/path/to/yarn.js`.

Support yarn execpath

---

bin/git/getCommitAndBranch.js

Strip `origin/*` prefix from branch name

---

bin/main.test.js
bin/tasks/report.js
bin/tasks/snapshot.js
bin/tasks/snapshot.test.js
bin/tasks/verify.js
bin/ui/messages/info/buildPassed.stories.js
bin/ui/tasks/snapshot.js
bin/ui/tasks/snapshot.stories.js

Update CLI to use new `test` terminology and statuses

---

bin/lib/getStorybookInfo.js
bin/lib/getStorybookInfo.test.js
bin/ui/messages/errors/noViewLayerDependency.js
bin/ui/messages/errors/noViewLayerDependency.stories.js
bin/ui/messages/errors/noViewLayerPackage.js
bin/ui/messages/errors/noViewLayerPackage.stories.js

Fixes #317
This makes installing the Storybook viewlayer package to node_modules optional when using `--storybook-build-dir`. We won't need the Storybook CLI in that case, so we don't care whether it's installed.
I also added explicit support for `@web/dev-server-storybook` which required a bit of a refactor.

Retrieve viewLayer and version from dependencies and support @web/dev-server-storybook

---

bin/tasks/build.js
bin/tasks/build.test.js
bin/ui/messages/errors/fatalError.js
bin/ui/tasks/build.js
bin/ui/tasks/build.stories.js
package.json

This uses `yarn-or-npm` to decide which client to use. It appears the original method doesn't work because I couldn't get it to use Yarn while running `yarn chromatic`. So rather than trying to detect the currently used client, this looks at the presence of yarn.lock (among other things) to determine the correct client.
Important detail: this means we'll be executing `npm run build-storybook` instead of `node /path/to/npm-cli.js run build-storybook`. It remains to be seen whether that will have an impact.

Fix `npx chromatic` timing out on build-storybook

---

bin/main.test.js
bin/tasks/build.js
bin/tasks/build.test.js

Restore original behavior to use npm_execpath

---

bin/tasks/build.js
bin/ui/messages/errors/buildFailed.js
bin/ui/messages/errors/buildFailed.stories.js

This might resolve the issue with node-sass.

Drop spawnOptions, including preferLocal: true

---

bin/io/setGlobalProxyAgent.js
bin/main.js
package.json
yarn.lock

Add support for proxy server

---

action/main.ts
bin/git/getCommitAndBranch.js
bin/ui/messages/errors/forksUnsupported.js
bin/ui/messages/errors/forksUnsupported.stories.js
bin/ui/messages/errors/gitOneCommit.js
bin/ui/messages/errors/missingGitHubInfo.js

Turns out we weren't setting the branch and slug properly for cross-fork builds in our GitHub Action.
Reported here: https://app.intercom.com/a/apps/zj7sn9j1/inbox/inbox/conversation/27253931490

Fix cross-fork builds from GitHub Action

---

bin/git/git.js
bin/lib/getDependentStoryFiles.js
bin/lib/getDependentStoryFiles.test.js
bin/tasks/upload.js
scripts/stats-to-story-files.js

This should fix `--only-changed` for monorepos (or any other case where Chromatic is executed from a subdirectory of the git repo).

Support resolving webpack stats in subdirectory

---

bin/io/getProxyAgent.js

Testing with 5.10.0 canary I hit issues on the proxy.
1. Initially, with the HTTP proxy on, I was seeing a runtime error related to the `URL` import
```
TypeError:
URL is not a constructor
at getProxyAgent (/Users/jmhobbs/Working/chromatic-cli/bin/io/getProxyAgent.js:12:23)
at HTTPClient.fetch (/Users/jmhobbs/Working/chromatic-cli/bin/io/HTTPClient.js:33:36)
at GraphQLClient.runQuery (/Users/jmhobbs/Working/chromatic-cli/bin/io/GraphQLClient.js:16:40)
at setAuthorizationToken (/Users/jmhobbs/Working/chromatic-cli/bin/tasks/auth.js:16:45)
at Task.task (/Users/jmhobbs/Working/chromatic-cli/bin/lib/tasks.js:13:13)
```
2. Secondly, my proxy server URL has a port in it, and `https-proxy-agent` appeared to be attempting to resolve the full host+port as a hostname (since `url.parse` returns both …

Fix runtime issues with HTTP_PROXY / NO_PROXY

---

bin-src/main.test.js
bin-src/tasks/gitInfo.js

This should prevent the GitHub action from throwing an error when it tries to call `toString()` on the exit code.
resolves #309

Sets exitCode 0 when branch is skipped with skip flag. 

---

bin-src/io/getProxyAgent.js

Our current code does not support using authenticated proxies, this change pulls out the username and password if present and configures `https-proxy-agent` to use those credentials.

Enable proxy authentication.  CH-813

---

bin-src/lib/getOptions.js
bin-src/lib/parseArgs.js
bin-src/tasks/snapshot.js
bin-src/tasks/upload.js
bin-src/tasks/verify.js
bin-src/ui/tasks/snapshot.js
bin-src/ui/tasks/snapshot.stories.js
bin-src/ui/tasks/upload.js
bin-src/ui/tasks/upload.stories.js
bin-src/ui/tasks/verify.js
bin-src/ui/tasks/verify.stories.js

This adds the `--dry-run` flag which will cause the CLI to skip the publish, verify and snapshot steps.
Useful if you just want to verify metadata detection and build behavior.

Add `--dry-run` to skip publishing CH-1068

---

.github/workflows/action-run.yml
.github/workflows/chromatic-action.yml
.github/workflows/chromatic-staging-action.yml
.github/workflows/chromatic-workflow_run.yml
action-src/README.md
action.yml

Remove the need to set a GitHub token

remove requirement for the token

---

bin-src/lib/uploadZip.js

Just a quick update to increase the sentinel file timeout to a minimum of 3 minutes to match the new Lambda timeout.

Increase unpack wait timeout to 3 minutes

---

bin-src/io/GraphQLClient.js
bin-src/tasks/report.js
bin-src/tasks/verify.js

Connections to the Chromatic backend can get a 503 return error from Heroku after 30 seconds which are then retried by our [HTTPClient](https://github.com/chromaui/chromatic-cli/blob/c3ac4603fb8e1532aae61e1e9081c426a1a14399/bin-src/io/HTTPClient.js#L39-L55). We want to lower our error rates to reduce noise in our monitoring by throwing errors before that occurs. Doing this returns a 200 from the fetch then we throw an error in our [GraphQLClient](https://github.com/chromaui/chromatic-cli/blob/c3ac4603fb8e1532aae61e1e9081c426a1a14399/bin-src/io/GraphQLClient.js#L24-L37). This allows known errors to retry again when creating a build!

Retry createBuild based on error messages

---

.github/workflows/action-run.yml

The action was using a wrong token which was triggering wrong chromatic builds for months!

fix: use correct project token for action workflow

---

bin-src/git/getCommitAndBranch.js
bin-src/git/getCommitAndBranch.test.js
bin-src/git/git.js
bin-src/main.test.js
bin-src/tasks/gitInfo.js
bin-src/tasks/upload.test.js
bin-src/ui/messages/errors/missingGitHubInfo.js
bin-src/ui/messages/info/customGitHubAction.js
bin-src/ui/messages/info/customGitHubAction.stories.js
bin-src/ui/messages/warnings/noCommitDetails.js
bin-src/ui/messages/warnings/noCommitDetails.stories.js

When passing the commit SHA using an environment variable (either explicitly or by using GitHub Actions or Travis), also set the committer name / email or show a warning when the given commit isn't found in history.

Set commit details when using env var and warn if it's missing

---

bin-src/lib/getDependentStoryFiles.js

Previously, `--untraced` would not be respected for changes to package files, making it impossible to ignore those, regardless of where they are in the repository. This fixes that.
I also dropped an outdated comment.

Fix untracing changed package files

---

bin-src/git/git.js

This updates the log format to yield the author info, which is more correct for merge commits.

Use commit author info instead of committer info [CH-1282]

---

.github/workflows/smoke-test-action.yml
.github/workflows/smoke-test-node12.yml
.github/workflows/smoke-test-npx.yml
.github/workflows/smoke-test-windows.yml
.github/workflows/smoke-test-yarn-berry.yml
.github/workflows/smoke-test-yarn-canary.yml
.github/workflows/smoke-test-yarn-classic.yml
.github/workflows/smoke-test-yarn.yml
CHANGELOG.md
action-src/main.ts
action.yml
bin-src/lib/getOptions.js
bin-src/lib/parseArgs.js
bin-src/tasks/gitInfo.js
bin-src/ui/messages/errors/noCSFGlobs.js

Also adds `dryRun` to the GitHub Action options, as it was missing.
We need this for our own CI tests because we run the same build multiple times with various versions of the CLI. Right now our smoke tests are succeeding because they skip "due to rebuild".

Add `--force-rebuild` to prevent skipping on rebuild

---

bin-src/trace.js

The main Chromatic CLI has `--storybook-base-dir` and `--storybook-config-dir`. This PR updates the flags for `trace` to use the same names.
This can be a patch release because `trace` is undocumented, effectively in beta, and not part of anyone's CI job.

Fix consistent naming of flags for `trace` util

---

bin-src/lib/parseArgs.js
bin-src/trace.js

Revisited the help text. `--allow-console-errors` doesn't do anything anymore (it was originally used with JSDOM) so I moved that to deprecated options. We may want to eventually add `--exit-zero-on-errors` as an alternative.

Reformat help text and move `allowConsoleErrors` to deprecated options

---

bin-src/lib/setExitCode.js
bin-src/tasks/snapshot.js
bin-src/ui/tasks/snapshot.js
bin-src/ui/tasks/snapshot.stories.js

Currently it's getting lumped in with `FAILED` but they are two different things so I split them up.
Note I used the correct spelling here, but the Chromatic API still gives us the wrong spelling. Not sure what to do about that.
Docs update: https://github.com/chromaui/chromatic-docs/pull/102

Handle the `CANCELLED` build status separately

---

action-src/main.ts

This was leading to this error, I guess:
```
Cannot read property 'ref' of undefined
```
I'm actually not entirely sure how to reproduce.

Handle the case where both ref+sha are unset on workflow_dispatch

---

bin-src/io/getProxyAgent.js

We need to use our own proxy to push to chromatic. This is specified with a host and subpath. But the pathname gets ignored. Maybe you could included that. We would appreciate.

also use pathname for creating proxy.

---

bin-src/lib/checkForUpdates.ts
bin-src/lib/spawn.ts
bin-src/main.test.ts

Fixes #512
This attempts to retrieve the current registry url using `npm config get registry` or the Yarn equivalent. Failing that, it falls back to the default registry url for npm.

Add support for custom npm registry url

---

bin-src/lib/getDependentStoryFiles.test.ts
bin-src/lib/getDependentStoryFiles.ts

Fixes https://github.com/chromaui/chromatic-cli/issues/519.
Ref: https://github.com/storybookjs/storybook/pull/17486

Add turbosnap support for `generated-stories-entry.cjs`

---

CHANGELOG.md
bin-src/lib/getDependentStoryFiles.test.ts
bin-src/lib/getDependentStoryFiles.ts

I'm on a mission to use turbosnap in my own project, which is built using storybook-builder-vite.  It's going to take a few different pieces:
- A rollup plugin to generate something similar to `preview-stats.json` from webpack.  
- Some changes to storybook-builder-vite (https://github.com/eirslett/storybook-builder-vite/pull/239)
- A few tweaks here to chromatic, to account for a few differences between webpack and vite.

Add TurboSnap support for Vite

---

action-src/main.ts

update the action's storybookUrl output, to NOT include `iframe.html` as requested in #409

Fix `storybookUrl` by removing `iframe.html` suffix

---

bin-src/lib/getDependentStoryFiles.test.ts
bin-src/lib/getDependentStoryFiles.ts
package.json

* https://github.com/chromaui/chromatic-cli/issues/486
* I'm developing in Monorepo
* I'm managing Storybook in a sub directory of my git root directory.
* Storybook 6.4.19
* Chromatic CLI v6.4.3
example
```
repo/
├── .git
└── sub
├── .storybook
├── assets
│   └── js
│       └── components
│           └── Button
│               ├── index.stories.tsx
│               └── index.tsx
├── package.json
└── yarn.lock
```
* When I run TurboSnap on v6.4.3, I get the following error message
* ```
Did not find any CSF globs in preview-stats.json
```
* In the current configuration, it doesn't seem to be able to find the dependent story files well
* When I looked at the output stats file, I found that the entry file was in the format `${baseDir}/generated-stories-entry.js`, so I fixed it that way
* …

Fix TurboSnap support for Storybook in a subdirectory

---

bin-src/lib/getDependentStoryFiles.test.ts
bin-src/lib/getDependentStoryFiles.ts
package.json

This PR fixes a bug related to situations where Chromatic (Turbosnap enabled) fails with the error "Did not find any CSF globs in preview-stats.json" (https://github.com/chromaui/chromatic-cli/issues/530 and https://github.com/chromaui/chromatic-cli/issues/486 - not sure if these are caused by the same error)
The error occurs if you're using Storybook 6.4 and pass in configDir as something else than '.' to Chromatic, and the reason stems from this array of predefined paths:
```ts
const storiesEntryFiles = [
// v6 store (SB <= 6.3)
`${storybookDir}/generated-stories-entry.js`,
// v6 store with root as config dir (or SB 6.4)
`generated-stories-entry.js`,
// v6 store with .cjs extension (SB 6.5)
'generated-stories-entry.cjs',
// v7 store (SB >= 6.4)
`storybook-stories.js`,
// vite builder …
```

fix: normalize storiesEntryFiles in getDependentStoryFiles

---

bin-src/git/git.ts

if the slug is capitalized we are accidentally treating it as a fork. Always downcasing the getSlug method should prevent that.
https://linear.app/chromaui/issue/CH-1630/chromatic-cli-slug-isnt-downcased

downcase the slug so we don't accidentally treat origin as fork

---

bin-src/__mocks__/unsupportedAddons/project.json
bin-src/lib/getPrebuiltStorybookMetadata.ts
bin-src/lib/getStorybookConfiguration.ts
bin-src/lib/getStorybookInfo.test.ts

You can test this by running `yarn test` and reviewing the "getStorybookInfo does not return with --storybook-build-dir unsupported addons in metadata" test.

Filter out unsupported addons from sb metadata

---

bin-src/lib/getOptions.test.ts
bin-src/lib/getOptions.ts
bin-src/lib/startStorybook.ts
bin-src/main.test.ts
bin-src/tasks/start.test.ts
bin-src/tasks/start.ts

Rather than just assuming `iframe.html` will exist where we expect it to be, actually resolve the provided URL and add `iframe.html` to the resolved (redirected) URL.

Handle redirects when using `--storybook-url`

---

package.json
scripts/release.js

And implement another way to ensure we build when only publishing the action

Restore prepublish script to fix smoke tests

---

bin-src/ui/messages/info/buildPassed.stories.ts
bin-src/ui/messages/info/buildPassed.ts

When using the Github Action, the flag `exitZeroOnChanges` is equal to true when not set explicitly equal to false. So, if the build status is `ACCEPTED`, `PENDING` or `DENIED`, we always return 'No visual changes were found in this build.' even if there was changes. This PR updates the message so if changes are found, the number of changes are shown in action output.

Add change count to buildPassed message if changes exist.

---

bin-src/lib/supportedAddons.ts

This should be considered a supported addon and I think it was left out by mistake

Add addon-interactions to supportedAddons in cli

---

bin-src/tasks/read-stats-file.ts
bin-src/tasks/upload.test.ts
bin-src/tasks/upload.ts
bin-src/trace.ts
bin-src/trim-stats-file.test.ts
bin-src/trim-stats-file.ts

This builds off of the changes to the `trim-stats-file`.
We are now moving to change all instances of the stats file to use `readStatsFile` which will read stats files from a stream.
This will allow handling larger stats files and avoid hitting a file size limit.

Update stats process to use stream

---

action-src/main.ts
action.yml
bin-src/lib/getOptions.ts
bin-src/lib/parseArgs.ts
bin-src/tasks/verify.ts
bin-src/types.ts
bin-src/ui/messages/errors/invalidOnly.stories.ts
bin-src/ui/messages/errors/invalidOnlyStoryNames.stories.ts
bin-src/ui/messages/errors/invalidOnlyStoryNames.ts
bin-src/ui/messages/info/listingStories.ts
bin-src/ui/messages/warnings/deprecatedOption.ts
bin-src/ui/tasks/snapshot.stories.ts
bin-src/ui/tasks/snapshot.ts
bin-src/ui/tasks/verify.stories.ts
bin-src/ui/tasks/verify.ts

Contrary to `--only`, `--only-story-names` can be specified multiple times.

Rename `--only` to `--only-story-names` but keep it as a deprecated alias

---

bin-src/git/getParentCommits.ts
bin-src/io/GraphQLClient.ts

This should deal with network flake and handle brief outages at the upstream Git provider (for up to several minutes).

Retry queries by default and allow even more retries for `FirstCommittedAtQuery`

---

bin-src/lib/getOptions.ts

It is always set to an array.
Fix issue introduced in https://github.com/chromaui/chromatic-cli/pull/643

Check `onlyStoryNames` is non-empty

---

bin-src/lib/getDependentStoryFiles.test.ts
bin-src/lib/getDependentStoryFiles.ts
package.json
tsconfig.json

If the name of a module in the Webpack Stats file has a URL parameter (e.g. ?ngResource) in it, it causes an issue with tracing the file. This PR resolves the issue.

Dealing with URL Params in stats file module names

---

action-src/main.ts

This avoids dumb mistakes by automatically exposing all properties on Chromatic's return value in GitHub Actions.

Ensure all GitHub Action outputs are exposed

---

CHANGELOG.md
bin-src/tasks/verify.ts
bin-src/types.ts
bin-src/ui/messages/errors/buildHasErrors.stories.ts
bin-src/ui/messages/errors/buildHasErrors.ts

This PR includes 
* Updating the test storybook to 6.5.12 and adding an interaction test
* Requesting an additional field on Build for the verify step which helps to show more accurate interaction test failure messaging in buildHasErrors

Update buildHasErrors with interaction test failure specific messaging

---

.github/workflows/chromatic-main-and-prs.yml

This PR adds an example yml configuration for when a user wants to really optimize the use of Chromatic with TurboSnap including:
* Disabling full re-builds when a global package file has changed
* Running only on push to main or the default base branch (`main, master, develop`)
* Running only on an active Pull request

Added an example for a TurboSnap optimized flow

---

action-src/main.ts
action.yml

This PR adds `onlyStoryFiles` as an option for the GitHub Action.
It is included as an option on the [Chromatic CLI docs](https://www.chromatic.com/docs/cli#chromatic-options).

Added onlyStoryFiles to the github action

---

action.yml

Node 12 actions are deprecated. This update the node version used to `node16`

Update action to use node16

---

package.json
yarn.lock

- Updated actions core as set-ouput was not explicitly called anywhere
- Ran tests. Tests passed 
Fixes #653 
Via https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
My bad on doing this to the wrong repo initially @kylegach

Update action core to ensure secure api usage for set-output

---

action-src/main.ts
action.yml

This is a follow on to #651 so that we also include this info in the github action output

add interactionTestFailuresCount to github action output

---

CHANGELOG.md
bin-src/lib/getDependentStoryFiles.ts
bin-src/trace.ts

In #648 we started looking within package manifest files and only bailing from TurboSnap if the change was dependency-related. However the `trace` command was failing because we were looking for info that didn't exist. 
Now we throw an error if a person attempts to trace a package.json file, since we'd need to know the file contents (and not just the file path) to know if that file would cause changes to story files.
New error message:

Trace command errors for package manifest change

---

bin-src/ui/messages/errors/gitOneCommit.ts

A lot of customers write in to support when their builds fail due to one commit. This ticket is to improve the messaging.

Improve the failure message when there's only one git commit

---

bin-src/lib/parseArgs.ts

Reverts chromaui/chromatic-cli#671
This is breaking CLI version reporting, among others.

Revert "Don't bundle package.json but rely on meow's runtime value instead"

---

action-src/main.ts
action.yml
bin-src/git/getCommitAndBranch.ts
bin-src/lib/getOptions.test.ts
bin-src/lib/getOptions.ts
bin-src/lib/getPrebuiltStorybookMetadata.ts
bin-src/lib/parseArgs.ts
bin-src/tasks/gitInfo.ts
bin-src/types.ts
bin-src/ui/messages/errors/fetchError.stories.ts
bin-src/ui/messages/errors/invalidOwnerName.stories.ts
bin-src/ui/messages/errors/invalidOwnerName.ts
bin-src/ui/messages/errors/invalidRepositorySlug.stories.ts
bin-src/ui/messages/errors/invalidRepositorySlug.ts
package.json

This allows customers to override the repository owner and/or name through either the `repositorySlug` flag/option, or the `branchName` flag/option, whichever is more convenient. Either of them can affect the `ownerName`, which is used to determine whether a build originates from a fork.
We didn't previously expose the `branchName` option on the GitHub Action, now we do.
For example:
- `repositorySlug: "chromaui/chromatic"` sets the owner name to `chromaui` and repository name to `chromatic`
- `branchName: "chromaui:feature"` sets the owner name to `chromaui` and the branch name to `feature`.
If both specify an owner name, they must match.

Add `--repository-slug` flag to CLI, and `repositorySlug` + `branchName` options to Action

---

action-src/main.ts

The support for `workflow_dispatch` added in #311, but it is a pain to set `inputs` manually.
This should be possible to automate, so I modified the implementation.

Omit `inputs` for `workflow_dispatch` event in GitHub Action

---

action-src/main.ts
package.json

This PR adds support for the following events
- `issue_comment`: This will allow the Github action to run if the user specifies the issue_comment event in their action. If the user specifies this event, the Chromatic Github action will run anytime someone creates a comment on an issue or pull request.
If a user only wants to run Chromatic on pull request comments, they will have to do something like this below.
```
on: issue_comment
jobs:
chromatic-deployment:
runs-on: ubuntu-latest
if: ${{ github.event.issue.pull_request }}
steps:
- uses: actions/checkout@v1
- name: Install dependencies
run: yarn
- name: Publish to Chromatic
uses: chromaui/action@v1
with:
projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
```

[Action] Add support for new issue_comment event

---

.github/workflows/chromatic-main-and-prs.yml
.github/workflows/chromatic-prod.yml
.github/workflows/chromatic-staging.yml
.github/workflows/smoke-test-action.yml
.github/workflows/smoke-test-node14.yml
.github/workflows/smoke-test-npx.yml
.github/workflows/smoke-test-windows.yml
.github/workflows/smoke-test-yarn-berry.yml
.github/workflows/smoke-test-yarn-canary.yml
.github/workflows/smoke-test-yarn-classic.yml
.github/workflows/smoke-test-yarn.yml
bin-src/lib/getEnv.ts

The Verify task essentially waits on the extract process to finish in Chromatic. However, it seems that there has been a delay in the background task processing. Hopefully, this creates some room until the Platform team can adjust the background task processing.

Increase timeout on Storybook Verify

---

bin-src/lib/getOptions.ts
package.json

Only Story Names was using preserve missing in the background. This updates the CLI so that the CLI flag no causes preserveMissingSpecs to be set.

Disconnect Preserve missing from `--only-story-names` flag

---

bin-src/lib/getStorybookMetadata.ts
package.json

Our telemetry reports storybook_version = null for a large proportion of our build events. It turns out these are SB v7 build events and the findBuilder function was erroring out causing the entire metadata Promise.all to fail. This PR updates the logic for finding the builder which should restore the telemetry overall.

get the builder name and version via the mainConfig for SB v7+

---

bin-src/lib/getStorybookInfo.test.ts
bin-src/lib/getStorybookMetadata.ts
package.json
yarn.lock

This PR bumps the Snyk lockfile parsing dependency and tweaks how we are getting the SB metadata.

Bump Snyk Lockfile Parser Dependency

---

node-src/lib/tasks.ts
node-src/types.ts

Telescoping on https://github.com/chromaui/chromatic-cli/pull/755
And ability to pass options to the node API.
This will allow us to get access to the context at the completion of each task, in particular to get the build id at the end of the `announce` task.

Added `onTaskComplete` callback option

---

package.json

I'm not sure why these utilities were in deps, no dev deps. I think that TSUP will never bundle deps, whereas maybe previously webpack would happily bundle everything? Not sure.

Move all depenendencies to dev deps

---

bin-src/main.ts

I missed this bit from the old code: https://github.com/chromaui/chromatic-cli/blob/b3fbf71511beb2dcb39da08cecc331e29614f7d3/bin-src/main.ts#L59-L60
Not sure if the log is still necessary but this solves the immediate problem

Ensure we exit with a code at the end

---

.github/workflows/chromatic-prod.yml
.github/workflows/chromatic-staging.yml
.github/workflows/smoke-test-action.yml
.github/workflows/smoke-test-node-api.yml
.github/workflows/smoke-test-node14.yml
.github/workflows/smoke-test-node16.yml
.github/workflows/smoke-test-npx.yml
.github/workflows/smoke-test-windows.yml
.github/workflows/smoke-test-yarn-berry.yml
.github/workflows/smoke-test-yarn-canary.yml
.github/workflows/smoke-test-yarn-classic.yml
.github/workflows/smoke-test-yarn.yml

This brings our project setup in line with our general advice to not hardcode project tokens.
Before we merge this, Azure Pipelines needs to be configured with the env var.
We should cycle our token once this PR is merged.

Use `CHROMATIC_PROJECT_TOKEN` environment variable rather than hardcoded value

---

node-src/git/git.ts

Ensure that Git commands are not timing out when running builds.

Increase the timeout for executing Git commands

---

action-src/main.ts

In the same vein as #196 and #668, but this time for the `release` event, preventing the following error:
```console
Error: release event is not supported in this action
```

Add `release` event to GitHub Action

---

node-src/index.ts
node-src/tasks/index.ts

To be used in https://github.com/chromaui/addon-visual-tests/pull/24

add getGitInfo function exported by the node-api

---

node-src/git/git.ts
node-src/index.ts
node-src/main.test.ts
node-src/tasks/gitInfo.test.ts
node-src/tasks/gitInfo.ts
node-src/types.ts
package.json

This is required for the "is outdated" concept in the Visual Tests addon, but may also be used in the future for other builds (e.g. during onboarding or even CI builds with an unclean working directory).

Calculate and record `uncommittedHash` when creating a build

---

node-src/git/getBaselineBuilds.ts
node-src/git/getParentCommits.test.ts
node-src/git/getParentCommits.ts
node-src/git/git.ts
node-src/index.ts
node-src/lib/emailHash.ts
node-src/lib/localBuildsSpecifier.ts
node-src/main.test.ts
node-src/tasks/gitInfo.test.ts
node-src/tasks/gitInfo.ts
node-src/tasks/initialize.ts
node-src/types.ts
node-src/ui/messages/errors/gitUserEmailNotFound.stories.ts
node-src/ui/messages/errors/gitUserEmailNotFound.ts
node-src/ui/messages/warnings/noCommitDetails.ts
package.json

Telescoping on https://github.com/chromaui/chromatic-cli/pull/795
We want to mark who created each build[1] so we can filter out local builds created by anyone else apart from the current user.
As such we:
- Send `gitUserEmaiHash ` as part of the `AnnounceBuild` mutation
- Send `localBuilds: { localBuildEmailHash: gitUserEmaiHash || committerHash }` as part of all the queries we use for baseline calculations.
This depends on https://github.com/chromaui/chromatic/pull/7576
[1] The creator is the current git user for local builds and the committer otherwise.

Pass `gitUserEmailHash` up with new builds and use `localBuilds` filter in baseline calculations

---

node-src/index.ts
node-src/runBuild.ts

I mistyped this, leading to an [unnecessary `as any` in the addon.](https://github.com/chromaui/addon-visual-tests/blob/ab11ced8628671c4ddbb495f9038d0d999cef3da/src/index.ts#L77)

If you supply options you don't need to supply them all

---

node-src/main.test.ts
node-src/tasks/snapshot.test.ts
node-src/tasks/snapshot.ts
node-src/types.ts

Previously, the CLI could crash if the `waitForBuild` polling happened to return a build while it was `PUBLISHED` or `PREPARED`. These would be considered "complete" (not in progress) but the code that runs after the build is complete (rightfully) does not handle those build statuses. 
I could've updated the status check to take `PUBLISHED` and `PREPARED` into account but it seems more resilient to look at `completedAt` instead.

Fix `Unexpected build status: PREPARED` error

---

node-src/index.ts
package.json

This adds `committedAt`, `committerName` and `committerEmail` to `GitInfo`, so that we can compare the last local commit against the `committedAt` of a build.

Include all commit info in `GitInfo`

---

node-src/tasks/snapshot.test.ts
node-src/tasks/snapshot.ts
node-src/tasks/upload.test.ts
node-src/tasks/upload.ts
node-src/types.ts
package.json

Currently only reported for tasks that can report meaningful progress. Open to changing the API.

Add a `onTaskProgress` option and report progress on it

---

node-src/main.test.ts
node-src/runBuild.ts
node-src/types.ts

Adds an option that receives an error when options or task fails. Consumes the same fatalError message that would be logged to CLI for a user error.

Add `onTaskError` option to report errors to node consumers

---

node-src/index.ts
node-src/lib/tasks.ts
node-src/tasks/auth.ts
node-src/tasks/build.ts
node-src/tasks/gitInfo.ts
node-src/tasks/initialize.ts
node-src/tasks/prepareWorkspace.ts
node-src/tasks/report.ts
node-src/tasks/restoreWorkspace.ts
node-src/tasks/snapshot.test.ts
node-src/tasks/snapshot.ts
node-src/tasks/storybookInfo.ts
node-src/tasks/upload.test.ts
node-src/tasks/upload.ts
node-src/tasks/verify.ts
node-src/types.ts
package.json

Rather than have the addon try to infer the current task from what's set on the context (or worse by reading the titles), let's just make everything explicit.

Add `onTaskStart`, and a new typed field `ctx.task`

---

node-src/index.ts
node-src/lib/log.ts
package.json
yarn.lock

We don't look at it as far as I am aware and it was causing an issue with this error: https://app.circleci.com/pipelines/github/chromaui/chromatic/26578/workflows/81195e51-d036-4244-aa8b-b62ad5e3dd75/jobs/267077

No longer log to loggly

---

node-src/lib/tasks.ts
node-src/main.test.ts
node-src/runBuild.ts
node-src/tasks/build.test.ts
node-src/tasks/build.ts
node-src/types.ts
node-src/ui/components/activity.ts
node-src/ui/messages/errors/buildCanceled.stories.ts
node-src/ui/messages/errors/buildCanceled.ts
package.json

Aborting the AbortSignal will gracefully cancel the build process. This will only work so long as the build isn't fully published yet, because at that point it's handed off to the capture cloud which doesn't yet support cancellation.
The build-storybook process is actually terminated. The upload should also be terminated (TODO).

Add `experimental_abortSignal` to Node API to allow canceling builds

---

node-src/git/git.test.ts
node-src/git/git.ts

If the user has `showSignature = true` configured for their Git environment, any invocation of `git log` will print additional information about the gpg signature, which causes an error. With this update, such gpg signature lines are ignored.
<details>
<summary>📦 Published PR as canary version: <code>7.2.4--canary.833.e6bcce9.0</code></summary>
<br />
```bash
npm install chromatic@7.2.4--canary.833.e6bcce9.0
yarn add chromatic@7.2.4--canary.833.e6bcce9.0
```
</details>

Gracefully handle gpg signature info in `git log` output

---

scripts/publish-action.mjs

<details>
<summary>📦 Published PR as canary version: <code>7.4.1--canary.837.6512947158.0</code></summary>
<br />
```bash
npm install chromatic@7.4.1--canary.837.6512947158.0
yarn add chromatic@7.4.1--canary.837.6512947158.0
```
</details>

Only release 'latest' GitHub Action from `main` branch

---

.github/workflows/check-labels.yml

This adds a GitHub workflow for [chromaui/pr-label-checker-action](https://github.com/chromaui/pr-label-checker-action), which I created for this. It's configured to require one of `patch` / `minor` / `major` as well as either `release` or `skip-release` and disallow the `DO NOT MERGE` label.
The purpose of this is to enforce having the necessary labels for `auto` to work properly.

Add workflow to require certain PR labels before merging

---

README.md
package.json

Releasing a `next` version wasn't quite working as expected. Seems like it needs the `prerelease` setting as well.
<details>
<summary>📦 Published PR as canary version: <code>7.5.4--canary.847.6655142677.0</code></summary>
<br />
```bash
npm install chromatic@7.5.4--canary.847.6655142677.0
yarn add chromatic@7.5.4--canary.847.6655142677.0
```
</details>

Configure auto with `prerelease` setting and update readme

---

node-src/index.test.ts
node-src/io/GraphQLClient.ts
node-src/lib/getOptions.ts
node-src/tasks/auth.test.ts
node-src/tasks/auth.ts
node-src/types.ts
node-src/ui/messages/errors/invalidProjectId.stories.ts
node-src/ui/messages/errors/invalidProjectId.ts
node-src/ui/tasks/auth.ts

Fixes AP-3383
Depends on https://github.com/chromaui/chromatic/pull/7913
This adds support for authentication via `projectId` and `userToken`, as an alternative to passing a `projectToken`. Currently only via the Node API (not as a flag).
This uses a new mutation `createCLIToken` on the public API to generate an "app token" that's compatible with the app token we'd otherwise get through the existing `createAppToken` mutation.
<details>
<summary>📦 Published PR as canary version: <code>7.6.1--canary.852.6771374764.0</code></summary>
<br />
```bash
npm install chromatic@7.6.1--canary.852.6771374764.0
yarn add chromatic@7.6.1--canary.852.6771374764.0
```
</details>

Support `projectId` + `userToken` as alternative to `projectToken` for auth

---

CHANGELOG.md
package.json

Auto messed up the last release, probably due to the `prerelease` setting. Let's get rid of it and disable `onlyGraduateWithReleaseLabel` as well, because it's not working as advertised. We can make do without any `next` releases.
<details>
<summary>📦 Published PR as canary version: <code>9.0.1--canary.854.6826342859.0</code></summary>
<br />
```bash
npm install chromatic@9.0.1--canary.854.6826342859.0
yarn add chromatic@9.0.1--canary.854.6826342859.0
```
</details>

Fix changelog for 9.0.0 and update auto config to prevent issue in the future

---

node-src/lib/utils.ts
node-src/lib/writeChromaticDiagnostics.test.ts
node-src/lib/writeChromaticDiagnostics.ts
node-src/ui/messages/errors/fatalError.stories.ts
node-src/ui/messages/errors/fatalError.ts

Redacts secret tokens in both diagnostics and fatal error output. We already had a `redact` function for this, I just moved it to utils for reuse and added `userToken` to the list of redacted fields.
<details>
<summary>📦 Published PR as canary version: <code>9.0.1--canary.859.6904794945.0</code></summary>
<br />
```bash
npm install chromatic@9.0.1--canary.859.6904794945.0
yarn add chromatic@9.0.1--canary.859.6904794945.0
```
</details>

Redact `userToken` in diagnostics and fatal error output

---

.github/workflows/chromatic-main-and-prs.yml
.github/workflows/chromatic-prod.yml
.github/workflows/chromatic-staging.yml
README.md
scripts/publish-action.mjs

This adds two additional tags when publishing the GitHub Action: `v*` and `v*.*.*` (e.g. `v9` and `v9.1.0`) besides the `latest` and `v1` (deprecated) tag we already have. This allows GitHub Action users to pin the CLI version to either a major release (which auto-upgrades but avoids breaking changes) or a patch release (which disables automatic upgrades altogether).
The release script still creates and force-pushes an entirely new repository without history, which means the commits for older tags will no longer exist in history. However, GitHub does retain these commits ([demonstrated here](https://github.com/chromaui/action-canary/commit/2ca473d66f1e2ba85e8c5f0b9d48dacb57d91c20)) and running the Action which such a version works normally ([demonstrated …

Support pinning GitHub Action to major or patch version

---

node-src/tasks/build.ts

It seems this can get set to `development` when builds are spawned from the Visual Tests addon. There's no reason to build in dev, AFAIK.
I guess technically this might be a breaking change, not sure.
<details>
<summary>📦 Published PR as canary version: <code>9.1.1--canary.865.7041382024.0</code></summary>
<br />
```bash
npm install chromatic@9.1.1--canary.865.7041382024.0
yarn add chromatic@9.1.1--canary.865.7041382024.0
```
</details>

Force `NODE_ENV=production` for Storybook builds through the CLI

---

node-src/git/getParentCommits.test.ts
node-src/git/getParentCommits.ts
node-src/git/mocks/double-loop.ts
node-src/git/mocks/mock-index.ts

When a Chromatic build is run on a squashed merge commit, there's no way to determine the source branch to look for ancestor builds since the git history is lost during the squash. To get around this, we try to query the git provider for a PR that resulted in the squashed commit, which will give us the information we need. 
We're currently only doing this lookup on the commit that a build is running on. This change increases the number of parent commits that we try to do the lookup on.
<details>
<summary>📦 Published PR as canary version: <code>10.0.1--canary.866.7107771516.0</code></summary>
<br />
```bash
npm install chromatic@10.0.1--canary.866.7107771516.0
yarn add chromatic@10.0.1--canary.866.7107771516.0
```
</details>

Increase number of commits checked for squash merge

---

node-src/index.test.ts
node-src/index.ts
node-src/lib/compress.ts
node-src/lib/upload.ts
node-src/lib/uploadFiles.ts
node-src/lib/uploadMetadataFiles.ts
node-src/lib/uploadZip.ts
node-src/tasks/report.ts
node-src/tasks/storybookInfo.test.ts
node-src/tasks/upload.test.ts
node-src/tasks/upload.ts
node-src/tasks/verify.test.ts
node-src/tasks/verify.ts
node-src/types.ts
node-src/ui/messages/errors/brokenStorybook.stories.ts
node-src/ui/messages/errors/brokenStorybook.ts
node-src/ui/messages/errors/fatalError.stories.ts
node-src/ui/messages/errors/fatalError.ts
node-src/ui/messages/errors/maxFileCountExceeded.stories.ts
node-src/ui/messages/errors/maxFileCountExceeded.ts
node-src/ui/messages/errors/maxFileSizeExceeded.stories.ts
node-src/ui/messages/errors/maxFileSizeExceeded.ts
node-src/ui/messages/info/storybookPublished.stories.ts
node-src/ui/messages/info/storybookPublished.ts
node-src/ui/tasks/upload.stories.ts
node-src/ui/tasks/upload.ts
package.json
yarn.lock

Depends on https://github.com/chromaui/chromatic/pull/8049
This uses the new `uploadBuild` mutation which uses S3 presigned POST requests for uploading and enforces strict file size limitations.
The mutation no longer returns the storybook base domain, instead we query for `storybookUrl` on the build. All references to `cachedUrl` and `isolatorUrl` have been replaced with `storybookUrl`.
<details>
<summary>📦 Published PR as canary version: <code>10.1.1--canary.876.7220703629.0</code></summary>
<br />
```bash
npm install chromatic@10.1.1--canary.876.7220703629.0
yarn add chromatic@10.1.1--canary.876.7220703629.0
```
</details>

Replace `getUploadUrls` with `uploadBuild` mutation

---

.github/workflows/release.yml
package.json
yarn.lock

Don't run `publish-action` on every merge to main, but only when `shipIt` has run (which depends on the `release` label being present on the PR).
This should prevent another situation where the GitHub Action is released with code that isn't actually supposed to be released yet (merged to main with the `skip-release` label).
<details>
<summary>📦 Published PR as canary version: <code>10.1.1--canary.877.7264235665.0</code></summary>
<br />
```bash
npm install chromatic@10.1.1--canary.877.7264235665.0
yarn add chromatic@10.1.1--canary.877.7264235665.0
```
</details>

Run publish-action script as afterShipIt hook

---

action-src/main.ts
action.yml

The Chromatic CLI can receive a `--config-file` configuration option.
This change exposes that same option in the GitHub action.

Add configFile option to GitHub Action 

---

node-src/lib/upload.ts
node-src/lib/waitForSentinel.ts
node-src/tasks/upload.test.ts
node-src/tasks/upload.ts

When publishing a Storybook with > 1000 files, the processing happens in batches. When using the `zip` option, each batch returns a `zipTarget`. However, if there are no files to upload for a batch, `zipTarget` will be `undefined`. Previously the CLI would use whatever `zipTarget` was returned last, even if that `zipTarget` is `undefined`. In this case, the CLI falls back to uploading individual files, but the `sentinelUrl` for unpacking the zip file will still be present and the CLI will wait for the unpack that will never happen, eventually timing out with a failed build.
This PR fixes the `zipTarget` by ignoring batches that have no `zipTarget`. Additionally, it deduplicates `sentinelUrls` because each batch returns the same basic `sentinelUrl`, with only a deviating query param …

Fix potential zip upload error when deduping files on a very large Storybook

---

action-src/main.ts
action.yml
node-src/index.test.ts
node-src/index.ts
node-src/lib/getConfiguration.ts
node-src/lib/getE2eBinPath.ts
node-src/lib/getOptions.ts
node-src/lib/setExitCode.ts
node-src/tasks/build.ts
node-src/types.ts
node-src/ui/messages/errors/missingDependency.stories.ts
node-src/ui/messages/errors/missingDependency.ts
package.json

When set, build storybook by directly invoking the binary from `@chromaui/test-archiver`.
This is a POC, we will move this binary into a `chromatic-playwright` package soon.
TODO:
Some notes:
- This won't work if you symlink the `chromatic` package into a test project (due to symlinking and resolution). Probably just use the canary to test it out (`chromatic@10.2.1--canary.882.7460727945.0`)
- For this to work in it's current form, you need to add the following export to the `@chromaui/archive-storybook` `package.json:exports` field:
```
"./package.json": {
"require": "./package.json",
"import": "./package.json"
}
```
I did this manually inside `node_modules` of my test project for now.
For some reason I couldn't `require.resolve('@chromaui/archive-storybook')` directly. @ndelangen may …

Add `--playwright` & `--cypress` flags

---

package.json

Storybook telemetry uses the package.json to determine the installed version of packages. Because the Chromatic CLI now has an exports map, but it does not contain package.json as an entry point, Storybook fails to read it, and therefore the version in the metadata is `null`. This PR fixes that!
Before:
After:
<details>
<summary>📦 Published PR as canary version: <code>10.5.1--canary.900.7652337120.0</code></summary>
<br />
```bash
npm install chromatic@10.5.1--canary.900.7652337120.0
yarn add chromatic@10.5.1--canary.900.7652337120.0
```
</details>

Add "package.json" to exports map

---

package.json

Temporarily disables releasing to GitHub Actions.
<details>
<summary>📦 Published PR as canary version: <code>10.6.1--canary.906.7674628239.0</code></summary>
<br />
```bash
npm install chromatic@10.6.1--canary.906.7674628239.0
yarn add chromatic@10.6.1--canary.906.7674628239.0
```
</details>

Remove after-release script

---

node-src/index.test.ts
node-src/index.ts

This PR adds a fallback for situations where we cannot get an origin URL to create a project slug. Without this, there's a downstream issue in the Visual Test Addon, where it thinks the project does not have git initialized, but it does. The project does not have an origin set yet.
To QA:
1. Run the tests.
2. Install this addon version (`1.0.4--canary.172.95c7a87.0`) in a repository where Git has been initialized, but there's no origin set yet.
3. Confirm that you see the "Git not detected" message.
4. Then, initialize the repo and make your first commit.
5. Confirm that you **_do not_** see the "Git not detected" message.
<details>
<summary>📦 Published PR as canary version: <code>10.7.1--canary.910.7751165821.0</code></summary>
<br />
```bash
npm …
```

Add Fallback getGitInfo if we cannot find the origin URL

---

node-src/lib/log.ts

Prefixes debug and file logs with timestamps, mostly so we get timing information for every part of the CLI process.
Also fixes a couple other logging issues such as formatting and crashing when attempting to unlink a nonexistent log file.
<details>
<summary>📦 Published PR as canary version: <code>10.7.2--canary.907.7780042745.0</code></summary>
<br />
```bash
npm install chromatic@10.7.2--canary.907.7780042745.0
yarn add chromatic@10.7.2--canary.907.7780042745.0
```
</details>

Add timestamps to debug and file logging

---

node-src/index.ts
node-src/types.ts

This PR will allow for "sessionid", "env" and "log" to be supplied to the node-interface via the options-object.
This as suggested by Gerrit.

Support `env`, `sessionId` and `log` options via Node API

---

node-src/index.ts
node-src/lib/getConfiguration.test.ts
node-src/lib/getConfiguration.ts

- Add `repositoryRootDir` field to `getGitInfo` return value
- Add `configFile` field to `getConfiguration` return value
- Rename `diagnosticFile` to `diagnosticsFile` in configuration schema (misspelling)
<details>
<summary>📦 Published PR as canary version: <code>10.8.0--canary.913.7802580624.0</code></summary>
<br />
```bash
npm install chromatic@10.8.0--canary.913.7802580624.0
yarn add chromatic@10.8.0--canary.913.7802580624.0
```
</details>

Expose `repositoryRootDir`, `configFile` and fix `diagnosticsFile`

---

node-src/lib/findChangedDependencies.test.ts
node-src/lib/findChangedDependencies.ts
node-src/lib/findChangedPackageFiles.ts
node-src/lib/log.ts
node-src/lib/utils.ts
node-src/tasks/gitInfo.ts
node-src/tasks/initialize.ts
node-src/tasks/upload.test.ts
node-src/tasks/upload.ts
node-src/types.ts
package.json

- Don't consider lockfiles at all if there are no traced changes to package metadata
- Otherwise, after figuring out what lockfile pairs exist, filter out the ones that don't have diffs.
In practice this makes a big difference:
- With no changes on the Chromatic monorepo it goes from 10-12s to 0s.
- With only `./package.json` changed, it goes to 1s.
<details>
<summary>📦 Published PR as canary version: <code>10.9.0--canary.912.7810229911.0</code></summary>
<br />
```bash
npm install chromatic@10.9.0--canary.912.7810229911.0
yarn add chromatic@10.9.0--canary.912.7810229911.0
```
</details>

Be smarter about comparing lock files

---

action-src/main.ts
node-src/index.test.ts
node-src/lib/getE2eBinPath.ts
node-src/lib/getE2eBuildCommand.ts
node-src/lib/getOptions.ts
node-src/tasks/build.ts
node-src/types.ts
node-src/ui/messages/errors/missingDependency.stories.ts
node-src/ui/messages/errors/missingDependency.ts

In the GitHub action, we cannot import peer dependencies (or anything really). However we should be able to `npm exec <bin-command>` inside the user's project dir, if the package is installed.
<details>
<summary>📦 Published PR as canary version: <code>10.9.1--canary.917.7824503990.0</code></summary>
<br />
```bash
npm install chromatic@10.9.1--canary.917.7824503990.0
yarn add chromatic@10.9.1--canary.917.7824503990.0
```
</details>

Directly execute build-archive-storybook if we can't resolve it

---

node-src/lib/getDependentStoryFiles.ts

The trace output in the debug logs results in too much noise and is not helpful.
I want to remove the log for the traced file so the debug log is functional again.
I ran this command `yarn chromatic trace -m expanded node-src/ui/components/activity.ts` to verify the `traceChanged` logic doesn't throw any errors.
I also ran this command without `-m expanded` and confirmed the trace logs no longer appear.
<details>
<summary>📦 Published PR as canary version: <code>10.9.3--canary.919.7845683347.0</code></summary>
<br />
```bash
npm install chromatic@10.9.3--canary.919.7845683347.0
yarn add chromatic@10.9.3--canary.919.7845683347.0
```
</details>

clean up debug log as it's too much noise

---

node-src/lib/getConfiguration.test.ts
node-src/lib/getConfiguration.ts

Add missing `traceChanged` config option to Chromatic config spec.
<details>
<summary>📦 Published PR as canary version: <code>10.9.1--canary.916.7821376194.0</code></summary>
<br />
```bash
npm install chromatic@10.9.1--canary.916.7821376194.0
yarn add chromatic@10.9.1--canary.916.7821376194.0
```
</details>

Allow `traceChanged` in Chromatic config spec

---

.github/workflows/chromatic-prod.yml
node-src/tasks/verify.ts
node-src/ui/messages/info/storybookPublished.stories.ts
node-src/ui/messages/info/storybookPublished.ts

This fixes a couple of issues with the Storybook published messaging.
1. Logging this from the `publishBuild` step meant that sometimes the `ctx.build` used to construct the message was in an early stage (like `PASSED`) without component and story information, resulting in a message like:
```
✔ Storybook published
We found undefined components with undefined stories.
```
2. This is also logged from the `verifyBuild` step under certain conditions (like with `exit-once-uploaded`), resulting in duplicate messaging like:
```
✔ Storybook published
We found undefined components with undefined stories.
✔ Storybook published
We found 19 components with 221 stories.
```
* With the canary version, commit some changes and run builds with various flags including with and without `exit-once-uploaded` …

Fix Storybook published messaging

---

.gitignore
node-src/git/getCommitAndBranch.ts
node-src/git/git.test.ts
node-src/git/git.ts

Amends change made to v10.0.0 with PR #863 to allow GitHub merge queue branches to be matched when they are using the "squash and merge" merge method. Currently, the branch name is expected to contain a known commit hash, but given commits can be squashed, the commit hash may not be known.
This change therefore loosens the branch name regex match to only check for a known pattern rather than assuming to find a specific commit hash within it. Once it finds the PR number, it can then find the original branch name as it is doing currently.
Fixes #871

Allow commit hash to not be known when finding merge queue PR number

---

.gitignore
node-src/git/getCommitAndBranch.ts
node-src/git/git.test.ts
node-src/git/git.ts

<details>
<summary>📦 Published PR as canary version: <code>11.0.1--canary.938.8157036058.0</code></summary>
<br />
```bash
npm install chromatic@11.0.1--canary.938.8157036058.0
yarn add chromatic@11.0.1--canary.938.8157036058.0
```
</details>

Allow commit hash to not be known when finding merge queue PR number [with github secrets]

---

node-src/tasks/report.test.ts
node-src/tasks/report.ts

This PR adds the functionality to generate the JUnit report with the default naming scheme if the flag is set to true.
To QA
1. Run `npx chromatic@11.0.1--canary.937.8150625203.0 -t=PROJECT_TOKEN --junit-report=true`
2. Run the Unit tests.
<details>
<summary>📦 Published PR as canary version: <code>11.0.2--canary.937.8160328696.0</code></summary>
<br />
```bash
npm install chromatic@11.0.2--canary.937.8160328696.0
yarn add chromatic@11.0.2--canary.937.8160328696.0
```
</details>

Fix support for boolean value to `junitReport` option

---

node-src/lib/checkStorybookBaseDir.ts
node-src/tasks/upload.test.ts

The CLI is supposed to spit out an error message like this:
```
✖ TurboSnap disabled until base directory is set correctly
The base directory allows TurboSnap to trace files.
Set the --storybook-base-dir option as the relative path from the repository root to the Storybook project root.
Run @chromatic-com/turbosnap-helper to get your base directory value.
```
But only the last line is showing unless the debug flag is enabled. This change fixes that.
QA by running this on a project using `--only-changed` and an invalid `--storybook-base-dir`.
<details>
<summary>📦 Published PR as canary version: <code>11.0.3--canary.932.8166399273.0</code></summary>
<br />
```bash
npm install chromatic@11.0.3--canary.932.8166399273.0
yarn add …
```

Display full error message when storybookBaseDir is invalid

---

node-src/tasks/upload.test.ts
node-src/tasks/upload.ts

onlyStoryFiles filenames that contain special characters are potentially treated as globs during the picomatch evaluation step of TurboSnap
e.g. `./example-(new).stories.js` => `./example-\\(new\\).stories.js`
This PR escapes those special characters so they are treated as the true filepath and not a glob.
<details>
<summary>📦 Published PR as canary version: <code>11.0.5--canary.942.8193831248.0</code></summary>
<br />
```bash
npm install chromatic@11.0.5--canary.942.8193831248.0
yarn add chromatic@11.0.5--canary.942.8193831248.0
```
</details>

escape special characters in onlyStoryFiles filenames

---

node-src/lib/setExitCode.ts
node-src/tasks/build.test.ts
node-src/tasks/build.ts
node-src/ui/messages/errors/e2eBuildFailed.stories.ts
node-src/ui/messages/errors/e2eBuildFailed.ts

Currently, any error thrown during the build step of an E2E build is treated as a missing dependency error, and the error message output is very specific to that. However, the build can fail for other reasons, such as archive directory not found. These other legit errors are swallowed and the resulting output is confusing.
This flips things around to try to determine if the error is due to a missing dependency, where the error usually has something to do about a command not being found. If the error message doesn't match, this will output a more generic error message that includes the original error message. 
**How to test**
* With a local project, install the canary CLI and try to run the chromatic command in both of the following scenarios and see that the errors are correct:
* With the …

Expose E2E build errors

---

node-src/lib/log.ts

Prevent non-string or null message from causing exit code 254 during build.

Prevent non-string or null message in timestamp logging from causing exit code 254 during build.

---

package.json

The `^0.5.2` version specifier will only match `0.5.x` versions, but we're at `0.6.x`.
<details>
<summary>📦 Published PR as canary version: <code>11.0.8--canary.943.8236202501.0</code></summary>
<br />
```bash
npm install chromatic@11.0.8--canary.943.8236202501.0
yarn add chromatic@11.0.8--canary.943.8236202501.0
```
</details>

Fix e2e peer dep versions

---

node-src/tasks/upload.ts
node-src/ui/messages/errors/missingStatsFile.stories.ts
node-src/ui/messages/errors/missingStatsFile.ts

Storybook 8 now supports generating stats for Vite projects, and so has updated the flag in order to not confuse Vite users. We should do likewise.
<details>
<summary>📦 Published PR as canary version: <code>11.0.9--canary.948.8260838530.0</code></summary>
<br />
```bash
npm install chromatic@11.0.9--canary.948.8260838530.0
yarn add chromatic@11.0.9--canary.948.8260838530.0
```
</details>

Tell SB8 users to pass `--stats-json` rather than `--webpack-stats-json`

---

.github/workflows/check-labels.yml
.github/workflows/chromatic-main-and-prs.yml
.github/workflows/chromatic-prod.yml
.github/workflows/chromatic-staging.yml
.github/workflows/release.yml
.github/workflows/smoke-test-action.yml
.github/workflows/smoke-test-node-api.yml
.github/workflows/smoke-test-node18.yml
.github/workflows/smoke-test-node20.yml
.github/workflows/smoke-test-npx.yml
.github/workflows/smoke-test-windows.yml
.github/workflows/smoke-test-yarn-berry.yml
.github/workflows/smoke-test-yarn-canary.yml
.github/workflows/smoke-test-yarn-classic.yml
.github/workflows/smoke-test-yarn.yml

This came recommended by [Checkov](https://github.com/bridgecrewio/checkov).
<details>
<summary>📦 Published PR as canary version: <code>11.0.9--canary.946.8261369317.0</code></summary>
<br />
```bash
npm install chromatic@11.0.9--canary.946.8261369317.0
yarn add chromatic@11.0.9--canary.946.8261369317.0
```
</details>

Restrict permissions in GitHub Action workflows

---

SUPPORT.md
node-src/tasks/build.ts
node-src/tasks/upload.ts

Codacy was complaining about some non-literal regexes. These use hardcoded values so they're safe, but that wasn't super obvious. I clarified that by using CONSTANT_CASE for these hardcoded values.
<details>
<summary>📦 Published PR as canary version: <code>11.0.9--canary.947.8261414908.0</code></summary>
<br />
```bash
npm install chromatic@11.0.9--canary.947.8261414908.0
yarn add chromatic@11.0.9--canary.947.8261414908.0
```
</details>

Fixes for various issues reported by Codacy

---

node-src/lib/checkForUpdates.ts
node-src/lib/getOptions.ts
node-src/lib/parseArgs.ts
node-src/types.ts

Added option (--skipUpdateCheck) to not check for an updated version of Chromatic. We have over a 100 of Storybook instances which we check with Chromatic. Our private NPM-registry-feed (Azure DevOps artifacts) does not support retrieving the version-info and triggers an error. Having these errors clutters our CI-logs.
This is a non-breaking change and can be marked as #patch

Add `skipUpdateCheck` option

---

node-src/types.ts
node-src/ui/messages/errors/fatalError.ts
package.json
scripts/publish-action.mjs

This restores the `afterShipIt` hook to automatically release the GitHub Action after releasing to npm. To prevent the wrong contents from being published, the publish-action script was updated to pull context (canary|next|latest) and package version number from the `ARG_0` environment variable provided by Auto, rather than trying to retrieve this info based on the Git branch and repository contents.
Furthermore, some log data was added for easier debugging.
<details>
<summary>📦 Published PR as canary version: <code>11.1.1--canary.956.8351561816.0</code></summary>
<br />
```bash
npm install chromatic@11.1.1--canary.956.8351561816.0
yarn add chromatic@11.1.1--canary.956.8351561816.0
```
</details>

Fix GitHub Action release script using data from Auto shipIt hook rather than from Git

---

action-src/main.ts

The syntax we currently propose for passing multiple values to an input in the GitHub Action is as follows:
```
externals: |
- '*.sass'
- 'public/**'
```
But that will be parsed into a single string with multiple lines that looks like this:
```
"- '*.sass'\n
- 'public/**'"
```
That won't behave as expected when passed along to the CLI.
The correct syntax for this should be like so:
```
externals: |
*.sass
public/**
```
That, along with the changes in this PR to use `getMultilineInput` to get those values will give us an array like we need:
```
["*.sass", "public/**"]
```
That can be passed along to the CLI, which expects a `string[]` for these inputs.
**How to test**
This has been published as `chromaui/action-canary@v1` and the CLI canary is below.
Try this out with no values for the …

Properly handle GitHub Action inputs that can have multiple values

---

node-src/lib/getOptions.test.ts
node-src/lib/getOptions.ts

Allows passing both --storybook-build-dir and  --build-script-name
Solves #933

Allow passing both `buildScriptName` and `storybookBuildDir`

---

node-src/lib/getOptions.test.ts
node-src/lib/getOptions.ts

For #934 to run GitHub Actions with environment secrets.
<details>
<summary>📦 Published PR as canary version: <code>11.2.0--canary.959.8356513389.0</code></summary>
<br />
```bash
npm install chromatic@11.2.0--canary.959.8356513389.0
yarn add chromatic@11.2.0--canary.959.8356513389.0
```
</details>

[trigger] Feature/allow build dir and build script name

---

scripts/publish-action.mjs

Auto shipIt's `newVersion` field is prefixed with `v` (e.g. `v11.2.0`), whilst the `version` field in package.json is not. This was causing the tags on the GitHub Action repo to be double-prefixed, e.g. `vv11.2.0`. Trimming the prefix from `newVersion` avoids that.
<details>
<summary>📦 Published PR as canary version: <code>11.2.1--canary.960.8357991504.0</code></summary>
<br />
```bash
npm install chromatic@11.2.1--canary.960.8357991504.0
yarn add chromatic@11.2.1--canary.960.8357991504.0
```
</details>

Trim `v` prefix from shipIt's version to avoid double prefixing tags

---

node-src/lib/getConfiguration.test.ts
node-src/lib/getConfiguration.ts

Fixes https://github.com/chromaui/addon-visual-tests/issues/247
If the Chromatic config file contains invalid JSON, a parse error is thrown in the CLI and printed by the Storybook process. The CLI did already have some handling of this scenario but it wasn't covering every type of JSON syntax error. This update will make it print a nicer error message that includes the config file path so people will know where to look.
<details>
<summary>📦 Published PR as canary version: <code>11.3.0--canary.961.8469857131.0</code></summary>
<br />
```bash
npm install chromatic@11.3.0--canary.961.8469857131.0
yarn add chromatic@11.3.0--canary.961.8469857131.0
```
</details>

Throw user-friendly error when config file fails to parse as JSON

---

node-src/git/git.ts
node-src/tasks/gitInfo.ts

A missing slug (caused by missing Git remote URL) is not a serious problem, so there is no need to log a warning for it. A debug message is more appropriate.
The patch build mechanism attempts to check for remote updates, which when failed should not prevent the patch build from running. In this case a warning _is_ appropriate because it might lead to unexpected results.
<details>
<summary>📦 Published PR as canary version: <code>11.2.1--canary.962.8479861319.0</code></summary>
<br />
```bash
npm install chromatic@11.2.1--canary.962.8479861319.0
yarn add chromatic@11.2.1--canary.962.8479861319.0
```
</details>

Suppress issues caused by missing Git remote

---

node-src/lib/checkStorybookBaseDir.test.ts
node-src/lib/checkStorybookBaseDir.ts

The `storybookBaseDir` option was being checked as a relative path, which caused `checkStorybookBaseDir` to fail when running Storybook from a subdirectory rather than the repository root. This PR ensures we use the repository root rather than the current working directory when checking the `storybookBaseDir` value.
<details>
<summary>📦 Published PR as canary version: <code>11.3.1--canary.974.8970353514.0</code></summary>
<br />
```bash
npm install chromatic@11.3.1--canary.974.8970353514.0
yarn add chromatic@11.3.1--canary.974.8970353514.0
```
</details>

Properly check `storybookBaseDir` against repository root rather than CWD

---

node-src/lib/checkStorybookBaseDir.test.ts
node-src/lib/checkStorybookBaseDir.ts

`getDependentStoryFiles` has always used the current working directory as base directory when `storybookBaseDir` isn't set, making it zero-config in most cases. `checkStorybookBaseDir` wasn't behaving in the same way, causing it to throw an error when it shouldn't. This update fixes this inconsistency by using the current working directory relative to the repository root as the default value for `storybookBaseDir`.
<details>
<summary>📦 Published PR as canary version: <code>11.3.2--canary.976.9002833958.0</code></summary>
<br />
```bash
npm install chromatic@11.3.2--canary.976.9002833958.0
yarn add chromatic@11.3.2--canary.976.9002833958.0
```
</details>

Use current working directory as default value for `storybookBaseDir`

---

package.json

(cherry picked from commit d75ed21efe58db1529a479183442b701f3863903)
I created a cherry-pick from the Fork since the CI process is failing on the Fork.
The original PR to fix the type import: https://github.com/chromaui/chromatic-cli/pull/984
<details>
<summary>📦 Published PR as canary version: <code>11.3.3--canary.986.9087708039.0</code></summary>
<br />
```bash
npm install chromatic@11.3.3--canary.986.9087708039.0
yarn add chromatic@11.3.3--canary.986.9087708039.0
```
</details>

Fix type declaration for `isChromatic` import

---

node-src/git/git.test.ts
node-src/git/git.ts
node-src/lib/findChangedDependencies.test.ts
node-src/lib/findChangedDependencies.ts

Fixes [#927](https://github.com/chromaui/chromatic-cli/issues/927)
When running from within a subdirectory (either cd-ing or setting `workingDir` on the GitHub Action), there is currently a bug with finding changed package manifest and lock files.
Given a repository structure like the following:
`package.json`
`yarn.lock`
`some-project/package.json`
`some-project/yarn.lock`
Currently, the manifest and lock files found for tracing changed dependencies will be relative to the current working dir. However, the list of manifest or lock files that have changed in the current commit will be relative to the repository root.
So if we're running Chromatic from within `some-project`, we will miss any changes to `some-project/package.json` because we'll be comparing the relative path of that file …

Fix dependency tracing when running from a subdirectory

---

node-src/git/git.test.ts
node-src/git/git.ts

When passing file paths to the `git ls-files` command to search for package manifest files, the paths are currently wrapped in single quotes.
This seems to be problematic on windows:
```
const results = await execGitCommand(`git ls-files --full-name -z 'C:/my/project/package.json'`);
console.log('execGitCommand results:', results);
...
execGitCommand results:
Done in 0.58s.
```
Switching to double quotes does the trick:
```
const results = await execGitCommand(`git ls-files --full-name -z "C:/my/project/package.json"`);
console.log('execGitCommand results:', results);
...
execGitCommand results: package.json
Done in 0.64s.
```
<details>
<summary>📦 Published PR as canary version: <code>11.3.5--canary.985.9099077866.0</code></summary>
<br />
```bash …
```

Use double quotes around command arguments

---

node-src/lib/e2e.ts

Removes a stray debugging log.
<details>
<summary>📦 Published PR as canary version: <code>11.3.6--canary.979.9173982602.0</code></summary>
<br />
```bash
npm install chromatic@11.3.6--canary.979.9173982602.0
yarn add chromatic@11.3.6--canary.979.9173982602.0
```
</details>

Remove console log

---

.circleci/config.yml
package.json
yarn.lock

This adds the [Slack plugin](https://intuit.github.io/auto/docs/generated/slack) for auto so it will send a webhook notification to our Slack whenever a new CLI version is released. The `SLACK_WEBHOOK_URL` secret has been setup for this repository.
<details>
<summary>📦 Published PR as canary version: <code>11.4.1--canary.990.9191631016.0</code></summary>
<br />
```bash
npm install chromatic@11.4.1--canary.990.9191631016.0
yarn add chromatic@11.4.1--canary.990.9191631016.0
```
</details>

Setup Slack plugin for auto to notify on new CLI releases

---

node-src/tasks/build.test.ts
node-src/tasks/build.ts

This should prevent the Storybook build script from prompting (e.g. to send a crash report), which would cause the CLI to hang. 
As an added bonus, [`preferLocal`](https://github.com/sindresorhus/execa/blob/main/docs/api.md#optionspreferlocal) might help ensure we use a locally installed package over a global one.
<details>
<summary>📦 Published PR as canary version: <code>11.4.1--canary.991.9225753804.0</code></summary>
<br />
```bash
npm install chromatic@11.4.1--canary.991.9225753804.0
yarn add chromatic@11.4.1--canary.991.9225753804.0
```
</details>

Pass `CI=1` environment variable to Storybook build command to disable prompts

---

.github/workflows/release.yml

Unfortunately the last release failed due a [missing Slack URL](https://github.com/chromaui/chromatic-cli/actions/runs/9254329865/job/25455887520). This URL is configures as an environment variable on the repo, but it needs to be explicitly passed to the release step in the GitHub Action.
<details>
<summary>📦 Published PR as canary version: <code>11.4.2--canary.992.9254693214.0</code></summary>
<br />
```bash
npm install chromatic@11.4.2--canary.992.9254693214.0
yarn add chromatic@11.4.2--canary.992.9254693214.0
```
</details>

Pass `SLACK_WEBHOOK_URL` to release script

---

bin-src/__mocks__/normalProjectJson/project.json
bin-src/__mocks__/sb6ProjectJson/project.json
bin-src/__mocks__/sb6ProjectJsonMissingBuilder/project.json
bin-src/init.test.ts
node-src/lib/getPrebuiltStorybookMetadata.test.ts
node-src/lib/getPrebuiltStorybookMetadata.ts
node-src/lib/getStorybookInfo.test.ts
node-src/lib/getStorybookMetadata.ts

There is a builder check in the storybook metadata, and SB 6 uses an object for the builder rather than the new format of a string value.
We added logic to handle both.
<details>
<summary>📦 Published PR as canary version: <code>11.5.1--canary.1001.9355178223.0</code></summary>
<br />
```bash
npm install chromatic@11.5.1--canary.1001.9355178223.0
yarn add chromatic@11.5.1--canary.1001.9355178223.0
```
</details>

Add fallback type for Storybook 6 builder syntax

---

.gitignore
package.json

The contents of `package.json` is compiled into the GitHub Action source code, so we need to clean that up as well.
<details>
<summary>📦 Published PR as canary version: <code>11.5.2--canary.1003.9395543210.0</code></summary>
<br />
```bash
npm install chromatic@11.5.2--canary.1003.9395543210.0
yarn add chromatic@11.5.2--canary.1003.9395543210.0
```
</details>

Clean package.json before compiling into source

---

.github/workflows/smoke-test-node18.yml
node-src/tasks/build.ts

Revert this small bit that was added in #991.
It was not necessary for the change made in that PR, and it caused the Storybook build command to run with the node version [specified by the GitHub Action](https://github.com/chromaui/chromatic-cli/blob/a1fb89f970745a6e55288603c09bf2015bb47766/action.yml#L151) (node 20), instead of the version of node that is installed in the workflow using something like `actions/setup-node`.
Fixes #1000
Fixes #1002
<details>
<summary>📦 Published PR as canary version: <code>11.5.4--canary.1006.9485918262.0</code></summary>
<br />
```bash
npm install chromatic@11.5.4--canary.1006.9485918262.0
yarn add chromatic@11.5.4--canary.1006.9485918262.0
```
</details>

Ensure GitHub Action runs in specified version of node

---

action-src/main.ts
action.yml
node-src/lib/getConfiguration.test.ts
node-src/lib/getConfiguration.ts

Add missing skipUpdateCheck option to config schema

---

node-src/git/findAncestorBuildWithCommit.test.ts
node-src/git/findAncestorBuildWithCommit.ts

Currently, we're reading the `build.uncommittedHash` value when determining a replacement build for a squash merge. Sometimes `build.uncommittedHash` is stored in the DB as an error string.
Not sure on the context around the `uncommittedHash` (how it's intended to be used/not used), but based on @tmeasday's suggestion we presumably only want to read the hash here if the build was local.
1. Install canary (see below) into test project
2. Run a build on `main` (`M.1`) with uncommitted changes (e.g. touch a readme or something). Check this build has `uncommittedHash !== ''`
3. Create branch
4. Create build on branch (build `B.1`)
5. Squash-merge branch
6. Do a fresh clone of repo, check out squash merge commit 
7. Run build for merge (build `M.2`) with `--debug` and `--only-changed`
Check …

Support non-local ancestor builds with `uncommittedHash`

---

node-src/index.test.ts
node-src/tasks/upload.test.ts
node-src/tasks/upload.ts

The original pattern to address the split of the special characters didn't account for the empty string at the beginning and end of the pattern. We only want to ignore empty strings in the middle of the string.
<details>
<summary>📦 Published PR as canary version: <code>11.6.0--canary.1016.10173197749.0</code></summary>
<br />
```bash
npm install chromatic@11.6.0--canary.1016.10173197749.0
yarn add chromatic@11.6.0--canary.1016.10173197749.0
```
</details>

Added logic to account for parentheses at the beginning

---

node-src/lib/findChangedDependencies.test.ts
node-src/lib/getDependencies.ts
package.json

There is an issue where the manifest tracing of package version dependencies doesn't work correctly if `strictOutOfSync` is set to true and always errors.
I'm flipping the flag to test it out and see if the manifest trace can get to a passing point.
Documentation for [Snyk Parser](https://github.com/snyk/nodejs-lockfile-parser)
<details>
<summary>📦 Published PR as canary version: <code>11.7.0--canary.1018.10185153847.0</code></summary>
<br />
```bash
npm install chromatic@11.7.0--canary.1018.10185153847.0
yarn add chromatic@11.7.0--canary.1018.10185153847.0
```
</details>

test setting outOfSync to false

---

node-src/lib/getConfiguration.test.ts
node-src/lib/getConfiguration.ts

We now offer the option to [validate the config file using JSON schema](https://www.chromatic.com/docs/cli/#chromatic-config-file). This PR allows the user to specify the schema within the config file itself. 
Fixes #1022
<details>
<summary>📦 Published PR as canary version: <code>11.7.1--canary.1023.10387892202.0</code></summary>
<br />
```bash
npm install chromatic@11.7.1--canary.1023.10387892202.0
yarn add chromatic@11.7.1--canary.1023.10387892202.0
```
</details>

Add  key to configuration to fix #1022

---

node-src/tasks/upload.test.ts
node-src/tasks/upload.ts

This is largely caused by using pre-built storybooks with the `-d` / `--storybook-build-dir` flag.  Filtering out this directory will prevent accidental upload of reserved files like trace metadata or processing sentinels.
<details>
<summary>📦 Published PR as canary version: <code>11.8.0--canary.1028.10715425881.0</code></summary>
<br />
```bash
npm install chromatic@11.8.0--canary.1028.10715425881.0
yarn add chromatic@11.8.0--canary.1028.10715425881.0
```
</details>

Don't upload files from `.chromatic` directory

---

node-src/tasks/build.test.ts
node-src/tasks/build.ts

This format is better supported by CLI wrappers (e.g. Angular) and prevents build errors.
<details>
<summary>📦 Published PR as canary version: <code>11.8.1--canary.1034.10797828139.0</code></summary>
<br />
```bash
npm install chromatic@11.8.1--canary.1034.10797828139.0
yarn add chromatic@11.8.1--canary.1034.10797828139.0
```
</details>

Use the `--flag=value` format for Storybook build options

---

.husky/pre-commit
package.json
yarn.lock

Just as the titles says. We've decided to remove the pre-commit hooks from this repo and lean on CI instead!
<details>
<summary>📦 Published PR as canary version: <code>11.9.1--canary.1039.10820173709.0</code></summary>
<br />
```bash
npm install chromatic@11.9.1--canary.1039.10820173709.0
yarn add chromatic@11.9.1--canary.1039.10820173709.0
```
</details>

Remove pre-commit hook

---

.github/workflows/chromatic-main-and-prs.yml
.github/workflows/chromatic-prod.yml

The v2 version is deprecated and now causing failures: https://github.com/chromaui/chromatic-cli/actions/runs/10832862998/job/30058245987
There are no breaking changes in v4 for how we use the action, so it should be a simple upgrade.
<details>
<summary>📦 Published PR as canary version: <code>11.10.1--canary.1042.10835327466.0</code></summary>
<br />
```bash
npm install chromatic@11.10.1--canary.1042.10835327466.0
yarn add chromatic@11.10.1--canary.1042.10835327466.0
```
</details>

Update actions/upload-artifact to v4

---

node-src/tasks/build.test.ts
node-src/tasks/build.ts

At 8.0.0, [`--webpack-stats-json` was renamed to `--stats-json`](https://github.com/storybookjs/storybook/blob/v8.0.0/MIGRATION.md#--webpack-stats-json-option-renamed---stats-json)
Prefer that option for projects using 8.0.0 or greater.
<details>
<summary>📦 Published PR as canary version: <code>11.10.1--canary.1035.10835841995.0</code></summary>
<br />
```bash
npm install chromatic@11.10.1--canary.1035.10835841995.0
yarn add chromatic@11.10.1--canary.1035.10835841995.0
```
</details>

Use --stats-json flag for SB 8.0.0+

---

node-src/lib/getStorybookInfo.test.ts

It appears we send a series of promises to search for various [view layers](https://github.com/chromaui/chromatic-cli/blob/b5e1dd39218f5ab477130ad1dd951149edc494b2/node-src/lib/viewLayers.ts) and use the first one to resolve. The problem with this test is we're using our own `node_modules` directory and we import two view layers from that list. Since the resolution of those promises is non-deterministic, this test can fail randomly.
To fix that problem, we can simply look for either option!
<details>
<summary>📦 Published PR as canary version: <code>11.10.2--canary.1043.10838513797.0</code></summary>
<br />
```bash
npm install chromatic@11.10.2--canary.1043.10838513797.0
yarn add chromatic@11.10.2--canary.1043.10838513797.0
```
</details>

Fix flaky missing dependency test

---

node-src/tasks/verify.test.ts

We had a flaky test which tests verify timeouts. We were returning the status `PUBLISHED` 3 times then `IN_PROGRESS` (which successfully resolves the `verifyBuild()` call). Instead, we can _always_ return a `PUBLISHED` build to avoid the timing issue.
<details>
<summary>📦 Published PR as canary version: <code>11.10.2--canary.1044.10838834040.0</code></summary>
<br />
```bash
npm install chromatic@11.10.2--canary.1044.10838834040.0
yarn add chromatic@11.10.2--canary.1044.10838834040.0
```
</details>

Fix flaky verify timeout test

---

node-src/tasks/build.test.ts
node-src/tasks/build.ts

Reverts chromaui/chromatic-cli#1035
<details>
<summary>📦 Published PR as canary version: <code>11.10.2--canary.1046.10847969470.0</code></summary>
<br />
```bash
npm install chromatic@11.10.2--canary.1046.10847969470.0
yarn add chromatic@11.10.2--canary.1046.10847969470.0
```
</details>

Revert "Use --stats-json flag for SB 8.0.0+"

---

.github/workflows/package-size.yml

We can later adapt this to track +/- changes over previous release.
<details>
<summary>📦 Published PR as canary version: <code>11.10.3--canary.1040.10851820355.0</code></summary>
<br />
```bash
npm install chromatic@11.10.3--canary.1040.10851820355.0
yarn add chromatic@11.10.3--canary.1040.10851820355.0
```
</details>

GitHub action to add package size comment to PR

---

eslint.config.mjs
node-src/io/GraphQLClient.ts
node-src/lib/compress.ts
node-src/lib/findChangedDependencies.ts
node-src/lib/getDependentStoryFiles.ts
node-src/lib/getStorybookMetadata.ts
node-src/lib/upload.ts
node-src/lib/uploadFiles.ts
node-src/lib/uploadZip.ts
node-src/tasks/report.ts

Simply enables our `unicorn/no-array-for-each` ESLint rule and fixes any errors that appear.
<details>
<summary>📦 Published PR as canary version: <code>11.10.3--canary.1048.10853398088.0</code></summary>
<br />
```bash
npm install chromatic@11.10.3--canary.1048.10853398088.0
yarn add chromatic@11.10.3--canary.1048.10853398088.0
```
</details>

Enable`unicorn/no-array-for-each` ESLint rule

---

eslint.config.mjs
node-src/index.test.ts
node-src/lib/getDependentStoryFiles.test.ts
node-src/tasks/upload.test.ts
node-src/tasks/upload.ts

Simply enables our `unicorn/prefer-string-raw` ESLint rule and fixes any errors that appear.
<details>
<summary>📦 Published PR as canary version: <code>11.10.3--canary.1050.10855415334.0</code></summary>
<br />
```bash
npm install chromatic@11.10.3--canary.1050.10855415334.0
yarn add chromatic@11.10.3--canary.1050.10855415334.0
```
</details>

Enable `unicorn/prefer-string-raw` ESLint rule

---

bin-src/trim-stats-file.ts
eslint.config.mjs
node-src/lib/e2e.ts
node-src/lib/findChangedPackageFiles.ts
node-src/lib/getDependentStoryFiles.ts
node-src/lib/getStorybookMetadata.ts
node-src/lib/promises.ts
node-src/tasks/gitInfo.ts
node-src/ui/messages/errors/uploadFailed.ts
node-src/ui/messages/info/listingStories.ts

Simply enables our `unicorn/no-array-callback-reference ` ESLint rule and fixes any errors that appear.
<details>
<summary>📦 Published PR as canary version: <code>11.10.3--canary.1051.10856015657.0</code></summary>
<br />
```bash
npm install chromatic@11.10.3--canary.1051.10856015657.0
yarn add chromatic@11.10.3--canary.1051.10856015657.0
```
</details>

Enable `unicorn/no-array-callback-reference` ESLint rule

---

eslint.config.mjs
node-src/git/getParentCommits.test.ts
node-src/git/git.ts
node-src/lib/getDependencies.test.ts
node-src/lib/getStorybookConfiguration.ts
node-src/tasks/report.ts
node-src/tasks/upload.ts
node-src/ui/messages/warnings/deviatingOutputDir.ts

Simply enables our `unicorn/better-regex` ESLint rule and fixes any errors that appear.
<details>
<summary>📦 Published PR as canary version: <code>11.10.3--canary.1055.10997453293.0</code></summary>
<br />
```bash
npm install chromatic@11.10.3--canary.1055.10997453293.0
yarn add chromatic@11.10.3--canary.1055.10997453293.0
```
</details>

Enable `unicorn/better-regex` ESLint rule

---

eslint.config.mjs
node-src/git/getParentCommits.ts
node-src/lib/getDependentStoryFiles.ts
node-src/tasks/index.ts
node-src/ui/messages/info/tracedAffectedFiles.ts

Simply enables our `unicorn/prefer-spread` ESLint rule and fixes any errors that appear.
<details>
<summary>📦 Published PR as canary version: <code>11.10.3--canary.1052.10911085616.0</code></summary>
<br />
```bash
npm install chromatic@11.10.3--canary.1052.10911085616.0
yarn add chromatic@11.10.3--canary.1052.10911085616.0
```
</details>

Enable `unicorn/prefer-spread` ESLint rule

---

.github/workflows/package-size-main.yml
.github/workflows/package-size.yml

Adds package size tracking against `main` via Upstash.
- Build CLI
- Get size of dist
- Set key for the current SHA in Upstash
- Get the current SHA of `main`
- Get the value of the main SHA from Upstash
- Update/Set comment with size of this PR, and the +/- from `main`
The `main` workflow just does the update to Upstash.
-----
<details>
<summary>📦 Published PR as canary version: <code>11.10.5--canary.1059.11021374226.0</code></summary>
<br />
```bash
npm install chromatic@11.10.5--canary.1059.11021374226.0
yarn add chromatic@11.10.5--canary.1059.11021374226.0
```
</details>

Track package size over time.

---

eslint.config.mjs
node-src/lib/compareBaseline.ts
node-src/lib/getDependencies.ts
node-src/lib/upload.ts
node-src/tasks/initialize.ts
node-src/ui/messages/info/tracedAffectedFiles.ts

Simply enables our `unicorn/no-array-reduce` ESLint rule and fixes any errors that appear.
<details>
<summary>📦 Published PR as canary version: <code>11.10.4--canary.1056.10999023014.0</code></summary>
<br />
```bash
npm install chromatic@11.10.4--canary.1056.10999023014.0
yarn add chromatic@11.10.4--canary.1056.10999023014.0
```
</details>

Enable `unicorn/no-array-reduce` ESLint rule

---

node-src/tasks/gitInfo.test.ts
node-src/tasks/gitInfo.ts
node-src/types.ts

Closes #1053 
In our FAQ section, we point out that customers can pull `storybookUrl` and `webUrl` from the `chromatic-diagnostics.json` file. Source: https://www.chromatic.com/docs/faq/get-published-storybook-url-via-ci/
However, this field isn't being set when a rebuild is found. To keep things easy on our customers, this adds those fields back in.
_Note: Turns out, we don't have documented output for our diagnostics because it's more of an internal debugging file. However, I opted to add a new field for `rebuildForBuild` with the details in case any customers were relying on `build` for something._
<details>
<summary>📦 Published PR as canary version: <code>11.11.0--canary.1060.11077751294.0</code></summary>
<br />
```bash
npm install …
```

Include `storybookUrl` and `webUrl` on skipped rebuild

---

bin-src/register.js
eslint.config.mjs
isChromatic.js
node-src/lib/checkStorybookBaseDirectory.test.ts
node-src/lib/compareBaseline.test.ts
node-src/lib/e2e.ts
node-src/lib/getDependencies.test.ts
node-src/lib/getStorybookMetadata.ts
node-src/tasks/report.test.ts
test-stories/timing.stories-disabled.js

Simply enables our `unicorn/prefer-module` ESLint rule and fixes any errors that appear.
Unfortunately, `import.meta.dirname` was unavailable so you have to grab it from `import.meta.url` 😞 
<details>
<summary>📦 Published PR as canary version: <code>11.11.1--canary.1061.11113701181.0</code></summary>
<br />
```bash
npm install chromatic@11.11.1--canary.1061.11113701181.0
yarn add chromatic@11.11.1--canary.1061.11113701181.0
```
</details>

Enable `unicorn/prefer-module` ESLint rule

---

action-src/main.ts
bin-src/main.ts
node-src/errorMonitoring.ts
node-src/index.ts
node-src/lib/checkForUpdates.ts
package.json
yarn.lock

This adds Sentry for error monitoring only, with opt-out through the environment variable `DISABLE_ERROR_MONITORING`.
The insertion of `Sentry.close` was required because most errors lead to immediate end of execution.
Additional tagging and annotation will come later.
<details>
<summary>📦 Published PR as canary version: <code>11.11.1--canary.1036.11128782068.0</code></summary>
<br />
```bash
npm install chromatic@11.11.1--canary.1036.11128782068.0
yarn add chromatic@11.11.1--canary.1036.11128782068.0
```
</details>

Add basic sentry integration to cli

---

node-src/index.ts

Moving/altering the `onError` in this flow should skip out of all the errors thrown by `getConfiguration` and `getOptions`
<details>
<summary>📦 Published PR as canary version: <code>11.11.1--canary.1067.11132677426.0</code></summary>
<br />
```bash
npm install chromatic@11.11.1--canary.1067.11132677426.0
yarn add chromatic@11.11.1--canary.1067.11132677426.0
```
</details>

Do not capture config/option exceptions

---

node-src/errorMonitoring.test.ts
node-src/errorMonitoring.ts
package.json
tsup.config.ts
yarn.lock

Removes ANSI escape codes from error and console log messages before being sent to Sentry.
Additionally, using `environment` for  the `cli`/`action` distinction was incorrect.  Move that to `entrypoint` and set a build time variable for `SENTRY_ENVIRONMENT` to bake it in appropriately.
<details>
<summary>📦 Published PR as canary version: <code>11.11.1--canary.1068.11147048454.0</code></summary>
<br />
```bash
npm install chromatic@11.11.1--canary.1068.11147048454.0
yarn add chromatic@11.11.1--canary.1068.11147048454.0
```
</details>

Filter ANSI escape codes for Sentry

---

node-src/errorMonitoring.ts
node-src/tasks/initialize.test.ts
node-src/tasks/initialize.ts
node-src/tasks/storybookInfo.ts

Collecting some additional context and tags for Sentry
- Index URL (if overridden)
- Storybook metadata
- App ID (after announce)
- Build ID (after announce)
- Package manager in use
<details>
<summary>📦 Published PR as canary version: <code>11.11.1--canary.1069.11148526667.0</code></summary>
<br />
```bash
npm install chromatic@11.11.1--canary.1069.11148526667.0
yarn add chromatic@11.11.1--canary.1069.11148526667.0
```
</details>

Annotate Sentry events

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

We have some internal tracking that leans on labels. Therefore, this adds the `CLI` label to all bug reports and feature requests. It also adds `Empathy` for all bug reports.
<details>
<summary>📦 Published PR as canary version: <code>11.11.1--canary.1071.11151105868.0</code></summary>
<br />
```bash
npm install chromatic@11.11.1--canary.1071.11151105868.0
yarn add chromatic@11.11.1--canary.1071.11151105868.0
```
</details>

Add `Empathy` and `CLI` labels to issue templates

---

.codacy.yaml

We're getting duplication errors from Codacy for our test files. We want to ignore those since we're okay with duplication there!
<details>
<summary>📦 Published PR as canary version: <code>11.11.1--canary.1073.11164367227.0</code></summary>
<br />
```bash
npm install chromatic@11.11.1--canary.1073.11164367227.0
yarn add chromatic@11.11.1--canary.1073.11164367227.0
```
</details>

Ignore duplication in test files and ignore all __mocks__

---

.circleci/config.yml

<details>
<summary>📦 Published PR as canary version: <code>11.11.1--canary.1078.11169365831.0</code></summary>
<br />
```bash
npm install chromatic@11.11.1--canary.1078.11169365831.0
yarn add chromatic@11.11.1--canary.1078.11169365831.0
```
</details>

Add TypeScript checking to CI pipeline

---

node-src/ui/messages/errors/gitNotInitialized.stories.ts
node-src/ui/messages/errors/gitNotInitialized.ts

It can be a little confusing when you try to run Chromatic in a directory that isn't a Git repo. You end up going through a couple of error steps before you finally get to a workable state. This adds a suggestion how to initialize an empty Git repo and add a single commit. Therefore, you only go through 1 error before you can run a build.
<details>
<summary>📦 Published PR as canary version: <code>11.12.0--canary.1081.11220007939.0</code></summary>
<br />
```bash
npm install chromatic@11.12.0--canary.1081.11220007939.0
yarn add chromatic@11.12.0--canary.1081.11220007939.0
```
</details>

Show steps for initializing a new Git repo

---

node-src/errorMonitoring.ts

No need for Sentry during development, so turn it off.
<details>
<summary>📦 Published PR as canary version: <code>11.11.1--canary.1082.11219638552.0</code></summary>
<br />
```bash
npm install chromatic@11.11.1--canary.1082.11219638552.0
yarn add chromatic@11.11.1--canary.1082.11219638552.0
```
</details>

Do not run Sentry in dev

---

node-src/tasks/snapshot.test.ts
node-src/tasks/snapshot.ts

Closes #973
If you pass something to `--exit-zero-on-changes`, the CLI assumes you're providing a branch name. However, if you pass `--exit-zero-on-changes=true`, it assumes `true` is the branch and essentially breaks the flag (unless your branch is literally `true`).
To account for this, we can simply check if the `--exit-zero-on-changes` contains the string `'true'` when we set the exit code on the snapshot step.
<details>
<summary>📦 Published PR as canary version: <code>11.11.1--canary.1083.11219791549.0</code></summary>
<br />
```bash
npm install chromatic@11.11.1--canary.1083.11219791549.0
yarn add chromatic@11.11.1--canary.1083.11219791549.0
```
</details>

Account for `--exit-zero-on-changes=true`

---

package.json
scripts/publish-action.mjs
scripts/publishAction.mjs
scripts/release.mjs
yarn.lock

We have quite a bit of indirection happening in the release pipeline. This turns that into a single script to manage everything instead of hooks via auto plugins.
<details>
<summary>📦 Published PR as canary version: <code>11.12.1--canary.1088.11243600462.0</code></summary>
<br />
```bash
npm install chromatic@11.12.1--canary.1088.11243600462.0
yarn add chromatic@11.12.1--canary.1088.11243600462.0
```
</details>

Move deployment to single script

---

CHANGELOG.md
package.json

We had some deployment struggles which caused `package.json` and `CHANGELOG.md` to get behind. This updates those quick!
<details>
<summary>📦 Published PR as canary version: <code>11.12.2--canary.1089.11257973439.0</code></summary>
<br />
```bash
npm install chromatic@11.12.2--canary.1089.11257973439.0
yarn add chromatic@11.12.2--canary.1089.11257973439.0
```
</details>

Manually update `package.json` and `CHANGELOG.md`

---

CHANGELOG.md
package.json

We had another bump in the road with our deployment pipeline so this updates `package.json` and `CHANGELOG.md` again so we can ensure the entire pipeline works.
<details>
<summary>📦 Published PR as canary version: <code>11.12.3--canary.1090.11258262264.0</code></summary>
<br />
```bash
npm install chromatic@11.12.3--canary.1090.11258262264.0
yarn add chromatic@11.12.3--canary.1090.11258262264.0
```
</details>

Manually update `package.json` and `CHANGELOG.md` v2

---

CHANGELOG.md
package.json

We had another bump in the road with our deployment pipeline so this updates `package.json` and `CHANGELOG.md` again so we can ensure the entire pipeline works.
The difference here is we're trying with the bot permissions set to `maintain` instead of `write`. This is supposed to give it the rights to push to a protected branch. 🤞 
<details>
<summary>📦 Published PR as canary version: <code>11.12.4--canary.1091.11260821216.0</code></summary>
<br />
```bash
npm install chromatic@11.12.4--canary.1091.11260821216.0
yarn add chromatic@11.12.4--canary.1091.11260821216.0
```
</details>

Manually update `package.json` and `CHANGELOG.md` v3

---

CHANGELOG.md
package.json

Either there's something up with the docs or there's something more strange happening. Let's try this again with even more permissions on the bot. 😞 
<details>
<summary>📦 Published PR as canary version: <code>11.12.5--canary.1092.11261040200.0</code></summary>
<br />
```bash
npm install chromatic@11.12.5--canary.1092.11261040200.0
yarn add chromatic@11.12.5--canary.1092.11261040200.0
```
</details>

Manually update `package.json` and `CHANGELOG.md` v4

---

scripts/release.mjs

According to https://github.blog/changelog/2023-09-13-github-actions-updates-to-github_ref-and-github-ref/ we now need to check for `refs/heads/main`, not `main`.
<details>
<summary>📦 Published PR as canary version: <code>11.12.6--canary.1093.11262656284.0</code></summary>
<br />
```bash
npm install chromatic@11.12.6--canary.1093.11262656284.0
yarn add chromatic@11.12.6--canary.1093.11262656284.0
```
</details>

Fix GITHUB_REF check on release

---

.github/workflows/smoke-test-node-api.yml
node-src/types.ts
node-src/ui/messages/info/tracedAffectedFiles.stories.ts
node-src/ui/messages/info/tracedAffectedFiles.ts

Previously we were printing `[object Object]` there, something must have shifted in the types.
This adds nice formatting for this object;
<details>
<summary>📦 Published PR as canary version: <code>11.12.6--canary.1095.11387612750.0</code></summary>
<br />
```bash
npm install chromatic@11.12.6--canary.1095.11387612750.0
yarn add chromatic@11.12.6--canary.1095.11387612750.0
```
</details>

Add nicer formatting to TS bail reasons.

---

.github/workflows/smoke-test-node-api.yml
node-src/tasks/upload.ts
node-src/ui/messages/errors/sentinelFileErrors.stories.ts
node-src/ui/messages/errors/sentinelFileErrors.ts

Adds useful information when a sentinel file check fails, which generally means there is a system outage.
Closes #1063
<details>
<summary>📦 Published PR as canary version: <code>11.12.7--canary.1094.11388633361.0</code></summary>
<br />
```bash
npm install chromatic@11.12.7--canary.1094.11388633361.0
yarn add chromatic@11.12.7--canary.1094.11388633361.0
```
</details>

Add context to sentinel upload failures.

---

.github/workflows/lint-and-test.yml
.github/workflows/smoke-test-action-next.yml
package.json
scripts/releaseNext.mjs

This adds a new status check for our merge queue that:
1. Pushes to the [action-next](https://github.com/chromaui/action-next) repo
2. Runs a test build against it
This should help catch any action-specific issues until we can put together a better system in the future.
<details>
<summary>📦 Published PR as canary version: <code>11.12.7--canary.1098.11406177933.0</code></summary>
<br />
```bash
npm install chromatic@11.12.7--canary.1098.11406177933.0
yarn add chromatic@11.12.7--canary.1098.11406177933.0
```
</details>

Add new check to test the CLI action in merge queue

---

.github/workflows/lint-and-test.yml
.github/workflows/smoke-test-action-next.yml

A continuation from #1098 from the findings of the latest merge queue tests:
1. Removes `on: merge_queue` from `lint-and-test` because that actually caused it to run _twice_ on merge
2. Updates the job name on `smoke-test-action-next` so the merge queue UI doesn't have `lint-and-test` multiple times
<details>
<summary>📦 Published PR as canary version: <code>11.12.7--canary.1100.11406787748.0</code></summary>
<br />
```bash
npm install chromatic@11.12.7--canary.1100.11406787748.0
yarn add chromatic@11.12.7--canary.1100.11406787748.0
```
</details>

Rename new action job name for merge queue UI

---

node-src/tasks/gitInfo.test.ts
node-src/tasks/gitInfo.ts
node-src/ui/messages/warnings/undefinedBranchOwner.stories.ts
node-src/ui/messages/warnings/undefinedBranchOwner.ts
package.json
yarn.lock

Sometimes our automatic CI detection lands us with an `undefined:<branch>` value, which is not correct.
This strips that from branch values (unless explicitly set), and prints a warning message so users can possibly switch to `CHROMATIC_BRANCH` and `CHROMATIC_SLUG`
Also upgrades `env-ci` to detect more CI builders and hopefully avoid this situation in the first place.
<details>
<summary>📦 Published PR as canary version: <code>11.12.7--canary.1101.11410238455.0</code></summary>
<br />
```bash
npm install chromatic@11.12.7--canary.1101.11410238455.0
yarn add chromatic@11.12.7--canary.1101.11410238455.0
```
</details>

Better handling of undefined values in branches

---

.github/workflows/pull-request-workflow.yml

We don't need `package-size` to run on anything that isn't a PR so we can skip these in the merge queue!
<details>
<summary>📦 Published PR as canary version: <code>11.13.1--canary.1105.11444002865.0</code></summary>
<br />
```bash
npm install chromatic@11.13.1--canary.1105.11444002865.0
yarn add chromatic@11.13.1--canary.1105.11444002865.0
```
</details>

Only run `package-size` on pull request

---

action-src/main.ts
action.yml
node-src/index.ts
node-src/lib/log.test.ts
node-src/lib/log.ts
node-src/lib/parseArguments.ts
node-src/types.ts
package.json

This is to allow the VTA to lower the log level and add a custom prefix to each log line in order to distinguish them from Storybook's own logs. The default prefix is a timestamp (e.g. `14:30:00.123`) in the local timezone.
Previously we would prefix each line with a UTC-based timestamp, but that only really worked when explicitly using the `--debug` or `--no-interactive` flag, or when writing to a log file. We now properly support `debug` and `interactive` as options to the logger as well. The logger no longer directly reads from `process.argv` but we pass in parsed arguments as flags instead. This doesn't affect existing setups except for GitHub Actions when using the `debug: true` or `interactive: false` option. Not a breaking change though.
Also we now preserve colors when using …

Add support for `logLevel` and `logPrefix` options, use local timestamp as default prefix

---

action-src/main.ts
action.yml
node-src/lib/getConfiguration.ts
node-src/lib/getOptions.ts
node-src/lib/parseArguments.ts
node-src/tasks/build.test.ts
node-src/tasks/build.ts
node-src/tasks/upload.ts
node-src/types.ts
node-src/ui/messages/errors/buildFailed.stories.ts
node-src/ui/messages/errors/buildFailed.ts
vitest.config.ts

Some monorepos are using `nx` to manage everything and they don't have a "scripts" field in their `package.json`. This prevents our [visual tests addon](https://github.com/chromaui/addon-visual-tests) from working.
To fix that issue, this introduces a new `--build-command` flag which can accept a full command to build the Storybook so you can do something like
```
yarn nx run my-app:build-storybook
```
<details>
<summary>📦 Published PR as canary version: <code>11.16.0--canary.1109.11520080155.0</code></summary>
<br />
```bash
npm install chromatic@11.16.0--canary.1109.11520080155.0
yarn add chromatic@11.16.0--canary.1109.11520080155.0
```
</details>

Add support for `--build-command` for arbitrary build commands

---

node-src/lib/getConfiguration.ts

<details>
<summary>📦 Published PR as canary version: <code>11.16.1--canary.1108.11522099593.0</code></summary>
<br />
```bash
npm install chromatic@11.16.1--canary.1108.11522099593.0
yarn add chromatic@11.16.1--canary.1108.11522099593.0
```
</details>

Handle ENOENT for bun as well as Node

---

README.md
docs/DEVELOPMENT.md
scripts/release.mjs

Just as the title says - this adds docs on how to run a separate project against your local copy of the CLI.
<details>
<summary>📦 Published PR as canary version: <code>11.16.4--canary.1113.11600333794.0</code></summary>
<br />
```bash
npm install chromatic@11.16.4--canary.1113.11600333794.0
yarn add chromatic@11.16.4--canary.1113.11600333794.0
```
</details>

Add steps for how to run builds against local CLI

---

node-src/index.test.ts
node-src/lib/log.ts
node-src/lib/writeChromaticDiagnostics.test.ts
node-src/lib/writeChromaticDiagnostics.ts

It's possible to send `--log-file` and `--diagnostics-file` to a random location that doesn't exist yet. In those cases, we were throwing a `ENOENT` error when attempting to write to the stream. This ensures the parent directory exists before we attempt to write those files!
<details>
<summary>📦 Published PR as canary version: <code>11.16.4--canary.1117.11636662323.0</code></summary>
<br />
```bash
npm install chromatic@11.16.4--canary.1117.11636662323.0
yarn add chromatic@11.16.4--canary.1117.11636662323.0
```
</details>

Ensure parent directory exists before writing log/diagnostics file

---

node-src/lib/getDependentStoryFiles.test.ts
node-src/lib/getDependentStoryFiles.ts
node-src/types.ts

At some point the `rsbuild` cache location changed which broke Turbosnap. Simply adding the new location to our list fixes that issue.
I also noticed the stats output is slightly different than Webpack/Vite so we lean on `resolvedModule` (which only exists in `rsbuild`) but fallback to `moduleName` when it doesn't exist.
Both of these changes allow `rsbuild` to work on the newer versions!
_Note: We've been doing some external testing with the canary and things are working great!_
<details>
<summary>📦 Published PR as canary version: <code>11.16.2--canary.1110.11566394830.0</code></summary>
<br />
```bash
npm install chromatic@11.16.2--canary.1110.11566394830.0
yarn add chromatic@11.16.2--canary.1110.11566394830.0
```
</details>

Account for `rsbuild` stats JSON output and multiple locations

---

node-src/index.test.ts
node-src/lib/getConfiguration.test.ts
node-src/lib/getConfiguration.ts
node-src/ui/messages/errors/unparseableConfigurationFile.stories.ts
node-src/ui/messages/errors/unparseableConfigurationFile.ts
package.json
yarn.lock

This adds support for JSON5 as a configuration file language, allowing for an extension to JSON that supports comments and other features.
Fixes CAP-2357.
Fixes #1114.
<details>
<summary>📦 Published PR as canary version: <code>11.17.0--canary.1118.11728459145.0</code></summary>
<br />
```bash
npm install chromatic@11.17.0--canary.1118.11728459145.0
yarn add chromatic@11.17.0--canary.1118.11728459145.0
```
</details>

:sparkles: Add support for JSON5 as a configuration file.

---

.github/ISSUE_TEMPLATE/bug_report.md

We want users that are having issues with Chromatic or the Chromatic platform to be more aggressively redirected to Chromatic support when they attempt to file an issue.
Refs CAP-2364.
<details>
<summary>📦 Published PR as canary version: <code>11.17.1--canary.1119.11732427490.0</code></summary>
<br />
```bash
npm install chromatic@11.17.1--canary.1119.11732427490.0
yarn add chromatic@11.17.1--canary.1119.11732427490.0
```
</details>

:book: Add new issue template that references Chromatic support.

---

node-src/git/git.test.ts
node-src/git/git.ts
node-src/index.test.ts
node-src/lib/getHasRouter.test.ts
node-src/lib/getHasRouter.ts
node-src/tasks/gitInfo.test.ts
node-src/tasks/gitInfo.ts
node-src/tasks/initialize.ts
node-src/tasks/storybookInfo.test.ts
node-src/tasks/storybookInfo.ts
node-src/types.ts

This PR is blocked on an index change (to come).
To QA:
- Create a routing based project (e.g. SB Next Sandbox)
- Run a build, check it sets `hasRouter=true`
- Create a non-routed project (e.g. `react-vite` Sandbox)
- Run a build, check it sets `hasRouter=false`
Use this review app: https://github.com/chromaui/chromatic/pull/9061
<details>
<summary>📦 Published PR as canary version: <code>11.17.0--canary.1112.11702183022.0</code></summary>
<br />
```bash
npm install chromatic@11.17.0--canary.1112.11702183022.0
yarn add chromatic@11.17.0--canary.1112.11702183022.0
```
</details>

Detect `context.projectMetadata.hasRouter` and send to the index

---

node-src/tasks/report.ts
package.json
yarn.lock

The status of particular test cases is now reported in the JUnit-formatted XML report. It is given as a `<property>` child element on the `<testcase>` element.
Refs CAP-2408.
<details>
<summary>📦 Published PR as canary version: <code>11.19.0--canary.1125.11957978468.0</code></summary>
<br />
```bash
npm install chromatic@11.19.0--canary.1125.11957978468.0
yarn add chromatic@11.19.0--canary.1125.11957978468.0
```
</details>

:sparkles: Add properties to XML reporting based on status.

---

bin-src/trace.ts
node-src/git/execGit.test.ts
node-src/git/execGit.ts
node-src/git/getParentCommits.ts
node-src/git/git.test.ts
node-src/git/git.ts
node-src/index.test.ts
node-src/lib/findChangedPackageFiles.test.ts
node-src/lib/findChangedPackageFiles.ts
node-src/lib/getDependentStoryFiles.test.ts
node-src/lib/getDependentStoryFiles.ts
node-src/lib/getHasRouter.test.ts
node-src/lib/getHasRouter.ts
node-src/lib/getStorybookBaseDirectory.test.ts
node-src/lib/getStorybookBaseDirectory.ts
node-src/lib/posix.ts
node-src/tasks/gitInfo.test.ts
node-src/tasks/gitInfo.ts
node-src/tasks/initialize.test.ts
node-src/tasks/initialize.ts
node-src/tasks/storybookInfo.test.ts
node-src/tasks/storybookInfo.ts
node-src/types.ts

Reverts chromaui/chromatic-cli#1121 (re-implements https://github.com/chromaui/chromatic-cli/pull/1112) and incorporates https://github.com/chromaui/chromatic-cli/pull/1120.
Also:
- added some error/timeout handling so we don't get stuck if there is something wrong with git.
- shorted timeouts to 5s as it's not critical this works (we could shorten further?)
- don't use `wc` or `head` as they may not be there. Instead:
- simulate `head -n 1` via streams
- just count the number of lines for `wc`. 
- This is inefficient as it requires loading all the lines into memory. 
- I'm not sure if this will be a problem or not if a repo has a heap of contributors or "app files".  
- I could implement another `execGitCommandCountLines` but I figured it was better to keep the complexity down.
Things to …

Send project metadata to the index

---

scripts/release.mjs

It appears we're accidentally pushing canary releases to the `latest` tag on the [action repo](https://github.com/chromaui/action) instead of matching what's in NPM. It appears there were 2 `release` actions that were ran around the same time:
1. Push to main: https://github.com/chromaui/chromatic-cli/actions/runs/12130149407
2. Update to PR tags (this pushed the canary version): https://github.com/chromaui/chromatic-cli/actions/runs/12130166324
We're currently filtering by branch which shows up as `main` on the action that pushed the incorrect version for some reason (perhaps because the original branch doesn't exist?). 
To fix that, we can add another check to only push `latest` when the action event is `push` and the branch is `main`.
<details>
<summary>📦 Published PR as canary …

Only publish `latest` action on push to main

---

action-src/main.ts

Fixes #1128 
In our Action, we default `exitOnceUploaded` to `false` which means any options set in a configuration are ignored. Instead, we can default it to `undefined` so things parse out later on (and account for config options).
Test runs with this branch:
- No config (waits for build): https://github.com/chromaui/chromatic-cli/actions/runs/12241546124/job/34146875208
- With config (doesn't wait for build): https://github.com/chromaui/chromatic-cli/actions/runs/12241558833/job/34146917373
<details>
<summary>📦 Published PR as canary version: <code>11.20.1--canary.1130.12241664568.0</code></summary>
<br />
```bash
npm install chromatic@11.20.1--canary.1130.12241664568.0
yarn add chromatic@11.20.1--canary.1130.12241664568.0
```
</details>

Account for configs when checking `exitOnceUploaded` in action

---

node-src/git/git.test.ts
node-src/git/git.ts
node-src/tasks/gitInfo.ts

Unintentionally, the steps to gather project metadata were causing builds to fail if there was an error. 
As this data is not required, we should not fail the whole process if one of these fail.
This appears to be the original intention (with existing try/catch) but async returns bypassed them.
Additionally, the timeout on `getCommittedFileCount` was reduced, as an up to 20s slowdown for non-critical information was too high.
<details>
<summary>📦 Published PR as canary version: <code>11.20.2--canary.1131.12281896012.0</code></summary>
<br />
```bash
npm install chromatic@11.20.2--canary.1131.12281896012.0
yarn add chromatic@11.20.2--canary.1131.12281896012.0
```
</details>

Errors in project metadata gathering causing build failures

---

.github/workflows/lint-and-test.yml
.github/workflows/pull-request-workflow.yml

This PR replaces Codacy with Codecov. You can test by going to the branch for this one in Codecov and seeing the coverage. Looks like vitest emits coverage for all files, not just executed ones, so we have a complete report by default.
Closes CAP-2546
<details>
<summary>📦 Published PR as canary version: <code>11.20.3--canary.1132.12396133002.0</code></summary>
<br />
```bash
npm install chromatic@11.20.3--canary.1132.12396133002.0
yarn add chromatic@11.20.3--canary.1132.12396133002.0
```
</details>

Upload coverage reports to codecov

---

node-src/index.ts
node-src/tasks/gitInfo.ts

When the action exits early due to an existing passed/accepted build for the commit, set the `storybookUrl` output to the value of the last build.
<details>
<summary>📦 Published PR as canary version: <code>11.21.0--canary.1134.12589333919.0</code></summary>
<br />
```bash
npm install chromatic@11.21.0--canary.1134.12589333919.0
yarn add chromatic@11.21.0--canary.1134.12589333919.0
```
</details>

Set `storybookUrl` action output on rebuild early exit

---

node-src/lib/getDependentStoryFiles.test.ts
node-src/lib/getDependentStoryFiles.ts

It's possible to make a change to `preview.js` and TurboSnap doesn't trigger a full rebuild (as seen with Vite projects). Instead, we want this to trigger a full rebuild to not miss anything.
1. Go to https://new-storybook.netlify.app/ and download the zip for the repo of a React Vite project.
2. Run `build` and then `build-storybook --stats-json`
3. Run npx `chromatic trace .storybook/main.ts` and notice the TurboSnap bail message outputs in the terminal (be sure to use the canary listed in this PR)
4. Run `npx chromatic trace .storybook/preview.tsx` and you should see the same bail message but pointing to `preview.tsx` (again, with the canary from this PR)
<details>
<summary>📦 Published PR as canary version: <code>11.22.0--canary.1133.12600382394.0</code></summary>
<br />
:sparkles: …

Bail on preview file changes

---

action-src/main.ts

Closes #1135
Simply adds the `outputDir` option to our GitHub Action so `buildCommand` can work properly. 
<details>
<summary>📦 Published PR as canary version: <code>11.22.1--canary.1136.12677624564.0</code></summary>
<br />
```bash
npm install chromatic@11.22.1--canary.1136.12677624564.0
yarn add chromatic@11.22.1--canary.1136.12677624564.0
```
</details>

Add `outputDir` to GitHub Action options

---

node-src/lib/getDependentStoryFiles.test.ts
node-src/lib/getDependentStoryFiles.ts
node-src/lib/getStorybookMetadata.ts

Closes #1137
Closes CAP-2412
This PR does a couple things:
1. Adds rsbuild v0.1.7 support
- The cache directory was flattened so TurboSnap would fail to find the CSF globs
2. Fixes our large debug log line
- That log line made it real tough to see if the TurboSnap change worked or not so I went ahead and fixed it
<details>
<summary>📦 Published PR as canary version: <code>11.22.2--canary.1138.12694282800.0</code></summary>
<br />
```bash
npm install chromatic@11.22.2--canary.1138.12694282800.0
yarn add chromatic@11.22.2--canary.1138.12694282800.0
```
</details>

Add rsbuild v0.1.7 support

---

node-src/lib/findChangedDependencies.test.ts
node-src/lib/getDependencies.test.ts
node-src/lib/getDependencies.ts

We've been seeing some OOM errors in TurboSnap that appears to come from our lock file parser. This attempts to alleviate that issue by completely skipping the lock file parsing if it's larger than 10 MB so we still get some of the benefits of TurboSnap without completely disabling it.
In case it wasn't obvious, the 10MB limit is a guess. We can adjust it as needed.
<details>
<summary>📦 Published PR as canary version: <code>11.23.0--canary.1140.12752995895.0</code></summary>
<br />
```bash
npm install chromatic@11.23.0--canary.1140.12752995895.0
yarn add chromatic@11.23.0--canary.1140.12752995895.0
```
</details>

Skip lock file parsing if it's larger than 10MB

---

node-src/lib/newRelic.ts
node-src/tasks/upload.ts

We want to monitor if our lock file parsing is still helping with TurboSnap. This adds some quick metrics to help us figure that out.
<details>
<summary>📦 Published PR as canary version: <code>11.24.0--canary.1141.12774591779.0</code></summary>
<br />
```bash
npm install chromatic@11.24.0--canary.1141.12774591779.0
yarn add chromatic@11.24.0--canary.1141.12774591779.0
```
</details>

Log Turbosnap metrics to New Relic

---

node-src/types.ts
node-src/ui/messages/errors/buildHasChanges.stories.ts
node-src/ui/messages/errors/buildHasChanges.ts
node-src/ui/messages/info/buildPassed.stories.ts
node-src/ui/messages/info/buildPassed.ts

Not yet connected to anything, but stubbed out the UI.
<details>
<summary>📦 Published PR as canary version: <code>11.25.2--canary.1145.12958352683.0</code></summary>
<br />
```bash
npm install chromatic@11.25.2--canary.1145.12958352683.0
yarn add chromatic@11.25.2--canary.1145.12958352683.0
```
</details>

Account for accessibility change counts in UI

---

node-src/lib/getDependentStoryFiles.test.ts
node-src/lib/getDependentStoryFiles.ts

Add an entrypoint we missed for rspack tracing.
Closes #1146
<details>
<summary>📦 Published PR as canary version: <code>11.25.2--canary.1147.13036792280.0</code></summary>
<br />
```bash
npm install chromatic@11.25.2--canary.1147.13036792280.0
yarn add chromatic@11.25.2--canary.1147.13036792280.0
```
</details>

Add additional rspack builder entrypoint

---

bin-src/trace.ts

The `trace` command was not putting the flag values where they belong, leading to a lot of confusion when tracing projects in sub-directories.  The main Chromatic command works as intended.  H/T @codykaup for finding this.
<details>
<summary>📦 Published PR as canary version: <code>11.25.3--canary.1148.13066235606.0</code></summary>
<br />
```bash
npm install chromatic@11.25.3--canary.1148.13066235606.0
yarn add chromatic@11.25.3--canary.1148.13066235606.0
```
</details>

Fix directory flags for trace command.

---

node-src/index.ts

Noticed we didn't differentiate the CLI client in Apollo when debugging something, so I added required headers.
<details>
<summary>📦 Published PR as canary version: <code>11.25.3--canary.1151.13186700181.0</code></summary>
<br />
```bash
npm install chromatic@11.25.3--canary.1151.13186700181.0
yarn add chromatic@11.25.3--canary.1151.13186700181.0
```
</details>

Set Apollo GraphQL client identification headers

---

node-src/lib/getDependentStoryFiles.test.ts
node-src/lib/getDependentStoryFiles.ts

As discussed in https://github.com/storybookjs/storybook/pull/30522#issuecomment-2654298340, we're going to be removing the slashes from the `virtual:` path of our Vite builder at some point. This prepares for that change so TurboSnap will continue to work when that happens.
<details>
<summary>📦 Published PR as canary version: <code>11.25.3--canary.1155.13313018152.0</code></summary>
<br />
```bash
npm install chromatic@11.25.3--canary.1155.13313018152.0
yarn add chromatic@11.25.3--canary.1155.13313018152.0
```
</details>

Add new Vite builder entry for future SB versions

---

package.json
yarn.lock

We're looking to migrate to the dependency graph generation in `snyk-nodejs-lockfile-parser`. The first step is to upgrade so here it is!
<details>
<summary>📦 Published PR as canary version: <code>11.26.0--canary.1158.13527878481.0</code></summary>
<br />
```bash
npm install chromatic@11.26.0--canary.1158.13527878481.0
yarn add chromatic@11.26.0--canary.1158.13527878481.0
```
</details>

Upgrade to latest version of `snyk-nodejs-lockfile-parser`

---

node-src/lib/getDependentStoryFiles.test.ts
node-src/lib/getDependentStoryFiles.ts
node-src/types.ts

Newer versions of our webpack builder is now emitting `resolvedModule`, or perhaps always did in an undocumented manner.
This is generally not a problem, as we used `resolvedModule` for rspack and it is generally `null` from webpack, but when you have import cycles you can get a value which is not what we desire from it.
Removing it works with current rspack builders as well.

Fix moduleName resolution for Storybook files with import cycles.

---

node-src/lib/getDependencies.test.ts
node-src/lib/getDependencies.ts

The code from `snyk-nodejs-plugin` does not currently support multiple scanned projects, but we want to make sure we cover that in case of a package upgrade we miss.
<details>
<summary>📦 Published PR as canary version: <code>11.26.2--canary.1161.13639680647.0</code></summary>
<br />
```bash
npm install chromatic@11.26.2--canary.1161.13639680647.0
yarn add chromatic@11.26.2--canary.1161.13639680647.0
```
</details>

Throw on multiple scanned projects from snyk

---

bin-src/trace.ts
node-src/lib/turbosnap/compareBaseline.test.ts
node-src/lib/turbosnap/compareBaseline.ts
node-src/lib/turbosnap/findChangedDependencies.test.ts
node-src/lib/turbosnap/findChangedDependencies.ts
node-src/lib/turbosnap/findChangedPackageFiles.test.ts
node-src/lib/turbosnap/findChangedPackageFiles.ts
node-src/lib/turbosnap/getDependencies.test.ts
node-src/lib/turbosnap/getDependencies.ts
node-src/lib/turbosnap/getDependentStoryFiles.test.ts
node-src/lib/turbosnap/getDependentStoryFiles.ts
node-src/lib/turbosnap/index.test.ts
node-src/lib/turbosnap/index.ts
node-src/tasks/upload.test.ts
node-src/tasks/upload.ts
package.json
tsconfig.json
vitest.config.mts
yarn.lock

Closes CAP-2835
We want to isolate the TurboSnap functions to a local lib so things are easier to test and reason about. This change
- Adds `paths` to `tsconfig.json` so we can import any local lib via `@cli/<package_name>`
- Moves all TurboSnap files to `lib/turbosnap`
- Adds a couple tests to increase coverage of `index.ts`
Note: Further refactoring and cleanup will happen in separate PRs!
<details>
<summary>📦 Published PR as canary version: <code>11.27.1--canary.1162.13641777959.0</code></summary>
<br />
```bash
npm install chromatic@11.27.1--canary.1162.13641777959.0
yarn add chromatic@11.27.1--canary.1162.13641777959.0
```
</details>

Move TurboSnap to a local lib

---

node-src/lib/turbosnap/getDependentStoryFiles.test.ts
node-src/lib/turbosnap/getDependentStoryFiles.ts

Looks like we have a list of lockfiles and forgot to add pnpm-lock.yaml to it. This does just that!
<details>
<summary>📦 Published PR as canary version: <code>11.27.1--canary.1164.13679750904.0</code></summary>
<br />
```bash
npm install chromatic@11.27.1--canary.1164.13679750904.0
yarn add chromatic@11.27.1--canary.1164.13679750904.0
```
</details>

Add `pnpm-lock.yaml` to list of lockfiles

---

node-src/ui/messages/info/speedUpCI.ts

We previously suggested that users use the flag --exit-once-uploaded, but now that we have a workflow parameter for this, our github action can actually take advantage of reporting the correct way to pass this option.
Fixes CAP-2374.
<details>
<summary>📦 Published PR as canary version: <code>11.28.1--canary.1169.14247692752.0</code></summary>
<br />
```bash
npm install chromatic@11.28.1--canary.1169.14247692752.0
yarn add chromatic@11.28.1--canary.1169.14247692752.0
```
</details>

:pencil2: Update help text to reflect actual state of exitOnceUploaded.

---

node-src/index.ts
node-src/tasks/gitInfo.test.ts
node-src/tasks/gitInfo.ts
node-src/types.ts

This PR fixes an issue whereby reruns of the GitHub action, which a user might trigger after approving visual changes, would not provide updated values for things like `testCount`, `changeCount`, etc. This was happening because we were only pulling these values from the `ctx.build` field, if it was defined. This PR updates that logic to pull from `ctx.rebuildForBuild` if `ctx.build` is undefined. I've also added the relevant fields to the `LastBuildQuery` GQL query so we're pulling that information from the index.
I've verified through the Apollo GQL dashboard that the fields I've added to `LastBuildQuery` work as expected. I also ran a build with the CLI locally and triggered the `Skipping rebuild of an already fully passed/accepted build`, and confirmed that the relevant count values …

Return additional build info on action rerun

---

node-src/tasks/report.test.ts
node-src/tasks/report.ts

Builds can have more tests than our max limit so details can go missing in CI pipelines and generated reports. This uses paginated queries to gather all the tests in the build in those cases.
<details>
<summary>📦 Published PR as canary version: <code>11.28.1--canary.1175.14502061051.0</code></summary>
<br />
```bash
npm install chromatic@11.28.1--canary.1175.14502061051.0
yarn add chromatic@11.28.1--canary.1175.14502061051.0
```
</details>

Use pagination to get all tests in the build

---

bin-src/trace.ts
node-src/git/execGit.test.ts
node-src/git/execGit.ts
node-src/git/findAncestorBuildWithCommit.test.ts
node-src/git/findAncestorBuildWithCommit.ts
node-src/git/getChangedFilesWithReplacement.test.ts
node-src/git/getChangedFilesWithReplacement.ts
node-src/git/getCommitAndBranch.test.ts
node-src/git/getCommitAndBranch.ts
node-src/git/getParentCommits.test.ts
node-src/git/getParentCommits.ts
node-src/git/git.test.ts
node-src/git/git.ts
node-src/index.test.ts
node-src/index.ts
node-src/lib/checkStorybookBaseDirectory.ts
node-src/lib/log.ts
node-src/lib/testLogger.ts
node-src/lib/turbosnap/findChangedDependencies.test.ts
node-src/lib/turbosnap/findChangedDependencies.ts
node-src/lib/turbosnap/findChangedPackageFiles.test.ts
node-src/lib/turbosnap/findChangedPackageFiles.ts
node-src/lib/turbosnap/index.test.ts
node-src/lib/turbosnap/index.ts
node-src/tasks/gitInfo.ts
node-src/tasks/prepareWorkspace.test.ts
node-src/tasks/prepareWorkspace.ts
node-src/tasks/restoreWorkspace.ts

Reverts chromaui/chromatic-cli#1181
This change included a breaking change and therefore should've been a major release.
<details>
<summary>📦 Published PR as canary version: <code>11.28.4--canary.1183.15212967594.0</code></summary>
<br />
```bash
npm install chromatic@11.28.4--canary.1183.15212967594.0
yarn add chromatic@11.28.4--canary.1183.15212967594.0
```
</details>

Revert "Add git command logging and pass `--no-relative` to `git diff`."

---

node-src/index.ts
node-src/lib/log.test.ts
node-src/lib/log.ts
node-src/lib/writeChromaticDiagnostics.test.ts

Makes `createLogger` available as a Node.js API so that it can be used to provide the required `log` property for `getGitInfo` introduced in #1181.
<details>
<summary>📦 Published PR as canary version: <code>11.29.0--canary.1182.15213361592.0</code></summary>
<br />
```bash
npm install chromatic@11.29.0--canary.1182.15213361592.0
yarn add chromatic@11.29.0--canary.1182.15213361592.0
```
</details>

Export `createLogger` and make all arguments optional

---

bin-src/trace.ts
node-src/git/execGit.test.ts
node-src/git/execGit.ts
node-src/git/findAncestorBuildWithCommit.test.ts
node-src/git/findAncestorBuildWithCommit.ts
node-src/git/getChangedFilesWithReplacement.test.ts
node-src/git/getChangedFilesWithReplacement.ts
node-src/git/getCommitAndBranch.test.ts
node-src/git/getCommitAndBranch.ts
node-src/git/getParentCommits.test.ts
node-src/git/getParentCommits.ts
node-src/git/git.test.ts
node-src/git/git.ts
node-src/index.test.ts
node-src/index.ts
node-src/lib/checkStorybookBaseDirectory.ts
node-src/lib/log.ts
node-src/lib/testLogger.ts
node-src/lib/turbosnap/findChangedDependencies.test.ts
node-src/lib/turbosnap/findChangedDependencies.ts
node-src/lib/turbosnap/findChangedPackageFiles.test.ts
node-src/lib/turbosnap/findChangedPackageFiles.ts
node-src/lib/turbosnap/index.test.ts
node-src/lib/turbosnap/index.ts
node-src/tasks/gitInfo.ts
node-src/tasks/prepareWorkspace.test.ts
node-src/tasks/prepareWorkspace.ts
node-src/tasks/restoreWorkspace.ts
vitest.config.mts

Reintroduce #1181, but as a **major** version bump this time.
<details>
<summary>📦 Published PR as canary version: <code>12.0.0--canary.1184.15225740095.0</code></summary>
<br />
```bash
npm install chromatic@12.0.0--canary.1184.15225740095.0
yarn add chromatic@12.0.0--canary.1184.15225740095.0
```
</details>

Revert "Revert "Add git command logging and pass `--no-relative` to `git diff`.""

---

node-src/lib/getEnvironment.test.ts
node-src/lib/getEnvironment.ts

We want to ensure we're always attempting to connect to the notify service (even in dev/staging). Therefore, we decided to make this a generated field based on the Index URL.
With this change you can run without setting `CHROMATIC_NOTIFY_SERVICE_URL` and it will still use the notify service! 🎉 
<details>
<summary>📦 Published PR as canary version: <code>13.0.2--canary.1194.16005096843.0</code></summary>
<br />
```bash
npm install chromatic@13.0.2--canary.1194.16005096843.0
yarn add chromatic@13.0.2--canary.1194.16005096843.0
```
</details>

Dynamically generate `CHROMATIC_NOTIFY_SERVICE_URL`

---

node-src/tasks/snapshot.test.ts
node-src/tasks/snapshot.ts

Looks like if all tests are TurboSnapped, we still connect to the notify service and wait for a message. Since the build is immediately done, we won't get message. Therefore, it sits there until we hit the timeout and falls back to polling.
This completely skips the notify connect if there are no tests.
<details>
<summary>📦 Published PR as canary version: <code>13.1.1--canary.1196.16036362697.1</code></summary>
<br />
```bash
npm install chromatic@13.1.1--canary.1196.16036362697.1
yarn add chromatic@13.1.1--canary.1196.16036362697.1
```
</details>

Skip notify service if there are no tests

---

node-src/lib/turbosnap/findChangedDependencies.test.ts
node-src/lib/turbosnap/findChangedDependencies.ts

When running TurboSnap, we copy a bunch of files to a temp directory which is based on _relative_ paths of those files. These file paths are based on the repository root which works unless the process is sitting in a different working directory relative to those files.
This updates our paths to use absolute file paths instead. :tada:
<details>
<summary>📦 Published PR as canary version: <code>13.1.1--canary.1195.16035468380.0</code></summary>
<br />
```bash
npm install chromatic@13.1.1--canary.1195.16035468380.0
yarn add chromatic@13.1.1--canary.1195.16035468380.0
```
</details>

Copy package files with absolute paths

---

node-src/git/getCommitAndBranch.test.ts
node-src/lib/getStorybookInfo.test.ts
node-src/lib/testLogger.ts
node-src/lib/turbosnap/getDependentStoryFiles.test.ts
node-src/lib/turbosnap/index.test.ts
node-src/tasks/build.test.ts
node-src/tasks/gitInfo.test.ts
node-src/tasks/initialize.test.ts
node-src/tasks/prepare.test.ts
node-src/tasks/prepareWorkspace.test.ts
node-src/tasks/report.test.ts
node-src/tasks/snapshot.test.ts
node-src/tasks/upload.test.ts
node-src/tasks/verify.test.ts

This PR updates our `TestLogger` class to wrap its logging methods (info, error, etc.) in `vi.fn` spies. This allows us to replace various ad hoc test loggers throughout our unit tests (i.e., stuff like `const log = { info: vi.fn() }` with the `TestLogger` class and maintain existing vi-based assertions, as well as maintaining existing `TestLogger` assertions that rely on the `entries` array on the `TestLogger`.
N/A. Unit tests passing without adjusting existing assertions should be indication enough that it's working.
<details>
<summary>📦 Published PR as canary version: <code>13.1.3--canary.1197.16058531221.0</code></summary>
<br />
```bash
npm install chromatic@13.1.3--canary.1197.16058531221.0
yarn add chromatic@13.1.3--canary.1197.16058531221.0 …
```

Replace ad hoc test loggers with `TestLogger`

---

node-src/tasks/initialize.ts
node-src/ui/messages/errors/buildHasErrors.stories.ts
node-src/ui/messages/errors/buildHasErrors.ts

Improve links and messaging when onboarding and a build has errors.
<details>
<summary>📦 Published PR as canary version: <code>13.1.4--canary.1201.16891761821.0</code></summary>
<br />
```bash
npm install chromatic@13.1.4--canary.1201.16891761821.0
yarn add chromatic@13.1.4--canary.1201.16891761821.0
```
</details>

Show setup URL on build errors when onboarding.

---

bin-src/__mocks__/atFrameworkNameProjectJson/project.json
node-src/lib/getPrebuiltStorybookMetadata.test.ts
node-src/lib/getPrebuiltStorybookMetadata.ts

This PR fixes an issue in our logic mapping view layer packages and Storybook framework names that seems (as best I can tell, anyway) to be based on outdated `storybook build` output from SB6. See inline comment for more details.
I created a project that uses a prebuilt storybook in its `chromatic` call, using React, Vite, and `storybook@10.0.0-beta.2`, and verified 1) that before this fix, we see the erroneous error message referencing the `--webpack-stats-json` flag, and 2) after this fix, we get the appropriate error message:
I also tested this on the customer's reproduction repo (it's private, so I can't link it), and confirmed the correct error message is shown.
<details>
<summary>📦 Published PR as canary version: <code>13.1.5--canary.1204.17742984995.0</code></summary>
<br /> …

Handle framework names that specify full viewlayer packages

---

node-src/lib/turbosnap/getDependentStoryFiles.test.ts
node-src/lib/turbosnap/getDependentStoryFiles.ts

Recently, the dependency graph being built in the Storybook-rsbuild community package has changed, as has the dependency graph entry point.
https://github.com/rspack-contrib/storybook-rsbuild/issues/332
This results in users getting the Chromatic CLI error message `Did not find any CSF globs in **`.
This is the new format for the entry point:
```
{
"id": "./storybook-config-entry.js",
"name": "./storybook-config-entry.js + 1 modules",
"modules": [
{ "name": "./storybook-config-entry.js" },
{ "name": "./storybook-stories.js" }
],
"reasons": []
},
```
To accommodate this, I've added the `storybook-config-entry.js` to the mapping in our getDependentStoryFiles.
I also added the file to the test to ensure it's passing.
I tested it out locally on the chromatic-cli repo with the stats file I …

Updated the mapping for the storybook entry with a recent change in storybook-rsbuild
